### PR TITLE
go module update for release v0.2.1

### PR DESCRIPTION
**Pull request by lizthegrey**

### CODE REVIEW

**Comment by lizthegrey** [comment]
@rghetia please review as a maintainer; once approved, will construe your and @jmacd's stamp here as approval to drive the rest of the release merging/tagging process.

**Comment by iredelmeier** [comment]
This (and equivalent updates for future versions) should be unnecessary if we merge #420.

**Comment by lizthegrey** [comment]
> This (and equivalent updates for future versions) should be unnecessary if we merge #420.

As discussed in #420, it's a tradeoff between doing this step at every release, and making every customer do an override of the otel version rather than importing work out of box. We've decided to do the former (e.g. continue doing these releases)

**Comment by jmacd** [comment]
@lizthegrey you seem to be driving very well. If this is ready, I say go for it.

**Comment by lizthegrey** [comment]
Great. I'll cut this first thing e.g. 9am EST tomorrow morning. It's at end of my workday and I don't want to start something I can't finish tonight.

**Pull request merged**
