### PR TITLE
Fix typo in using instrumentation libraries markdown

### PR DESCRIPTION
**Pull request by bvwells**
Fix typo in using instrumentation libraries markdown

### CODE REVIEW

**Review by Aneurysm9 — APPROVED** [review]

**Comment by bvwells** [comment]
Thanks for the super fast review @Aneurysm9!

**Review by MrAlias — APPROVED** [review]

**Review by MadVikingGod — APPROVED** [review]

**Review by XSAM — APPROVED** [review]
lgtm

**Review by dashpole — APPROVED** [review]

**Review by pellared — APPROVED** [review]
Why not. I can also approve 😄

**Comment by bvwells** [comment]
Thanks @Aneurysm9, @MrAlias, @MadVikingGod, @XSAM, @dashpole and @pellared! Hope I didn't miss anyone! :-)

**Pull request merged**
