### PR TITLE
Remove flaky and redundant TestBatchSpanProcessorForceFlushTimeout

### PR DESCRIPTION
**Pull request by pellared**
`TestBatchSpanProcessorForceFlushTimeout` is flaky: https://github.com/open-telemetry/opentelemetry-go/actions/runs/5667616980/job/15356681512?pr=4366

The existing `TestBatchSpanProcessorForceFlushCancellation` is not flaky and tests the exactly same behavior.

## Testing

`TestBatchSpanProcessorForceFlushTimeout` is flaky:

```
$ go test -race -count=10000 -run TestBatchSpanProcessorForceFlushTimeout
--- FAIL: TestBatchSpanProcessorForceFlushTimeout (0.00s)
    batch_span_processor_test.go:560: expected "context deadline exceeded" error, got <nil>
FAIL
exit status 1
FAIL    go.opentelemetry.io/otel/sdk/trace      5.829s
```

`TestBatchSpanProcessorForceFlushCancellation` is stable

```
$ go test -race -count=10000 -run TestBatchSpanProcessorForceFlushCancellation
PASS
ok      go.opentelemetry.io/otel/sdk/trace      5.251s
```

### CODE REVIEW

**Comment by pellared** [comment]
Merging as this is trivial and can affect other PRs.

**Comment by MrAlias** [comment]
> The existing `TestBatchSpanProcessorForceFlushCancellation` is not flaky and tests the exactly same behavior.

That is not true though ... it tests that a cancelled context is handled, this tests a context that has exceeded its deadline is handled. They return different errors.

**Comment by MrAlias** [comment]
> Merging as this is trivial and can affect other PRs.

I'm not sure this was worth a quick merge instead of fixing the underlying test. It has existed for a long time and its failure was infrequent enough I think we could have spent the time to add a correct fix.

**Comment by pellared** [comment]
> > The existing `TestBatchSpanProcessorForceFlushCancellation` is not flaky and tests the exactly same behavior.
> 
> That is not true though ... it tests that a cancelled context is handled, this tests a context that has exceeded its deadline is handled. They return different errors.

There was valid "race" that force flush channel was handled before the timeout occurred.

The implementation has to simply correctly handle the context cancelation. It does not matter if it is timeout or other kind of cancelation.

**Comment by MrAlias** [comment]
> The implementation has to simply correctly handle the context cancelation. It does not matter if it is timeout or other kind of cancelation.

Does it handle a timeout? We used to have a test that showed it did :wink:

**Comment by pellared** [comment]
I have not noticed `<- ctx.Done()` in the test that I removed. I will double-check tomorrow. Maybe it is a bug... Thanks a lot ❤️

**Pull request merged**
