### PR TITLE
Metric label enrich

### PR DESCRIPTION
**Pull request by hstan**
This PR is a rework on https://github.com/open-telemetry/opentelemetry-go/pull/1271 based on @jmacd 's implementation in https://github.com/open-telemetry/opentelemetry-go/pull/1421

It adds an Enricher API that supports attaching baggage attributes as metric labels. 

More discussion can be found in the original PR review https://github.com/open-telemetry/opentelemetry-go/pull/1271
and https://github.com/open-telemetry/opentelemetry-go/pull/1271

### CODE REVIEW

**Comment by hstan** [comment]
@jmacd Could you please take a look when got a chance

**Comment by jmacd** [comment]
@hstan I haven't forgotten about this, but with the recent re-boot of OTel metrics taking place it's difficult to focus on enrichment. Would you be interested in attending one of the now weekly API/SDK SIG meetings? It's Thursdays on the OTel public calendar.

**Comment by hstan** [comment]
@jmacd No worries. Sure I'm more than happy to attend the meeting, could you send me an invitation? Thanks

**Comment by jmacd** [comment]
I can't figure out how to invite you -- without an e-mail address, and oddly I'm having trouble linking to an event on the OTel public calendar. 

https://calendar.google.com/calendar?cid=Z29vZ2xlLmNvbV9iNzllM2U5MGo3YmJzYTJuMnA1YW41bGY2MEBncm91cC5jYWxlbmRhci5nb29nbGUuY29t

There is a meeting this week on Thursday at 4pm PST (and every two weeks), which is probably your best bet.

**Comment by hstan** [comment]
> I can't figure out how to invite you -- without an e-mail address, and oddly I'm having trouble linking to an event on the OTel public calendar.
> 
> https://calendar.google.com/calendar?cid=Z29vZ2xlLmNvbV9iNzllM2U5MGo3YmJzYTJuMnA1YW41bGY2MEBncm91cC5jYWxlbmRhci5nb29nbGUuY29t
> 
> There is a meeting this week on Thursday at 4pm PST (and every two weeks), which is probably your best bet.

@jmacd I've got a team event today conflicts with the meeting, I'll try to join next time. btw my email is tanhanshuo<at>gmail.com

**Comment by MrAlias** [comment]
Closing as the metrics signal refactor at the specification level might make this work wasted. We can open again if the specification solidifies and it is determined needed.

**Pull request closed without merging**
