### PR TITLE
docs(website_docs): fix exporting_data.md and getting-started.md toc

### PR DESCRIPTION
**Pull request by Petrie**
l don't know why the markdown grammar "#" can't generate the write TOC, but the "##" can.
when I read the docs for the first time ,I have found the mistake,but I don't why.
Today, I compare this doc with the other languare instrumentation, I found the problem.

### CODE REVIEW

**Comment by Petrie** [comment]
Error in [check-links](https://github.com/open-telemetry/opentelemetry-go/runs/6647512686?check_suite_focus=true)  seem's not to be related with my change.   do you  know why? @hanyuancheung  😳

**Review by dmathieu — APPROVED** [review]
This makes sense. `#` should indicate the article's title, not subsections.

**Review by hanyuancheung — APPROVED** [review]
LGTM. Pls make sure the format is correct.

**Comment by dmathieu** [comment]
The link failure will be fixed by #2955.

**Comment by Petrie** [comment]
Thanks for reply @dmathieu @hanyuancheung . The latest code  have been merged for fix the link failure.

**Review by MrAlias — APPROVED** [review]

**Pull request merged**
