### PR TITLE
Small optimization to pass the actual length when make slice

### PR DESCRIPTION
**Pull request by zchee**
Small optimization to pass the actual length when `make` slice.
Depending on the situation, but this change will consume less memory.

---

When the src length is just a `slice` type:

```go
	// assume ss is pseudo struct slice:
	out := make([]string, len(ss))
	for i, s := range ss {
		out[i] = s.String()
	}
```

~When the src length is `map` type:~

```go
	type kv struct {
		key   string
		value string
	}
	// assume m is pseudo map[string]string:
	out := make([]kv, len(m))
	i := 0
	for k, v := range m {
		out[i] = kv{
			key:   k,
			value: v,
		}
		i++
	}
```

### CODE REVIEW

**Comment by dmathieu** [comment]
Can you run benchstat with the benchmarks and this branch?

**Comment by zchee** [comment]
@dmathieu I see, I'll take some benchmarks.

**Comment by Aneurysm9** [comment]
+1 to wanting to see benchmarks.  It looks like a capacity is already being set everywhere this change is made, so there shouldn't be any allocation savings and this new pattern introduces additional complexity in the form of the index variable that must be updated.  I've forgotten `i++` enough times that I'm wary of requiring that pattern unless the performance gain is substantial, and probably even then.

**Comment by zchee** [comment]
@Aneurysm9 I totally agree your opinions. I know some Go idioms have readability+maintainability vs performance.
If this change not affected perf (or smaller), I'll revert some changes.
I'm taking each package benchmark now. pls wait a while.

**Comment by zchee** [comment]
@Aneurysm9 cc: @dmathieu @MrAlias 
I took each benchmark but affected a bit (or nothing). So I reverted to using `i` indexing when the `map` case.

> I've forgotten i++ enough times that ...

I assume this comment is for the `map` case, WDYT?

**Comment by MrAlias** [comment]
My prior testing of this type of change has shown no significant performance difference. If you have found otherwise, please provide evidence. Otherwise, this should be closed.

**Pull request closed without merging**
