### PR TITLE
update stdout trace with resource.

### PR DESCRIPTION
**Pull request by rghetia**
This adds printing resources in the stdout exporter. The fix is not an elegant fix. resource.Resource fields are not exported. So instead of writing custom json.Marshal for entire SpanData I have wrapped it around an internal _SpanData containing original SpanData and the resources converted to a list of Attributes. _SpanData is then printed using standard json.Marshal.

### CODE REVIEW

**Comment by rghetia** [comment]
It might be better to convert Resource to Span Attributes on a copy of SpanData rather than the earlier solution of wrapping SpanData with another internal object. This is also inline with jaeger and zipkin (TBD).

@jmacd , @MrAlias  WDYT?

**Comment by jmacd** [comment]
Yes, that sounds good.

**Comment by MrAlias** [comment]
Makes sense to merge with the attributes if that is the plan for Zipkin and Jaeger. Wondering about the `Resource` field in the `SpandData`, should we keep a copy of the `Resource` after merging? Seems a bit redundant, but also more accurate than an empty field.

**Comment by rghetia** [comment]
> Makes sense to merge with the attributes if that is the plan for Zipkin and Jaeger. Wondering about the `Resource` field in the `SpandData`, should we keep a copy of the `Resource` after merging? Seems a bit redundant, but also more accurate than an empty field.

I'll remove it.

**Pull request merged**
