### PR TITLE
add RegisterSimpleSpanProcessor() modeled on stackdriver code

### PR DESCRIPTION
**Pull request by lizthegrey**
Code using API and Exporters only should not need sdktrace; thus, put this into the exporter code to hide sdktrace from the API user.

### CODE REVIEW

**Comment by jmacd** [comment]
I think this is moving us in the wrong direction.  There are two issues filed about avoiding the use of globals in the SDK:

https://github.com/open-telemetry/opentelemetry-go/issues/207
https://github.com/open-telemetry/opentelemetry-go/issues/171

I believe we should be constructing the SDK with a list of exporters, not registering them globally. If there are going to be multiple SDKs in use, they may want to be configured with different exporters. 

Can we instead let the SDK take a list of span processors / exporters at startup? I do not believe the application `main()` function is really interested in allowing arbitrary modules of code to register new exporters after initialization.

**Comment by lizthegrey** [comment]
This is a convenience set of functions and people can choose to register span processors with the tracer of their choice if they don't want the global tracer used.

**Comment by jmacd** [comment]
These globals are already interfering with our ability to test or run multiple simultaneous SDKs with different export configurations. I am arguing that we should eliminate the global list of span processors and let them be configured for each SDK independently. 

Secondly, I am arguing that there is no need to allow these to be registered on-the-fly that I am aware of, so it is simpler to pass these to the SDK constructor. There is no need for a global variable to coordinate the exporters or span processors belonging to an SDK.

As it stands, any of the default `sdk/trace` Tracers will use all exporters. This is not a convenience. There is not a current way to bind individual exporters to individual SDKs. I would like us to address #171 and #207 first, and then we should not need any global registration functions--there should only be one global "registration", the moment where the global tracer and meter are installed (https://github.com/open-telemetry/oteps/blob/master/text/0005-global-init.md).

**Comment by lizthegrey** [comment]
Can we hop on a video call to discuss? My aim here is to simplify and standardize the initialization interface e.g. ensuring that exact `Exporter` has a standard set of ways to create and register it.

I'm not hung up on the specifics of how it happens, aside from the fact that the current interface requiring us to manually create the `SimpleSpanProcessor` etc. is unwieldy and verbose. So I'm happy to accommodate what you'd like to do, either in this pull or waiting for you to make the SDK de-globalization changes and then harmonizing all the exporters.

**Comment by jmacd** [comment]
Here's a proposal that I think will satisfy #171, #207, and your concerns as well.

In the `sdk/trace` package, we will eliminate `Register()`.  We'll replace it with a `New(...) Tracer` method to return a new tracer implementation. The options `...` are:

`WithSyncExporter(export.SpanSyncer)` configures a synchronous exporter
`WithBatchExporter(export.SpanBatcher)` configures a batching exporter

these two helpers will automatically construct the appropriate simple or batch span processor. If a need exists for users to pass custom span processors (e.g., for a z-pages application), I expect we'll also want this option:

`WithSpanProcessor(trace.SpanProcessor)`  configure a custom span processor

And to replace the current `sdktrace.ApplyConfig`, a 

`WithConfig(sdktrace.Config)`

or this could be broken down in the functional option style as well, so 

`WithSampler(trace.Sampler)`

or whatever other configuration options there are. There are no SDK- or exporter-package globals in this proposal.

The returned `Tracer` can be used as a stand-alone tracer or it can be installed as the global tracer.

The whole snippet of code will read:

```
    tracer := sdktrace.NewTracer(sdktrace.WithConfig(...), sdktrace.WithSyncExporter(stdout.NewExporter()))
    meter := sdkmeter.NewMeter(...)
    opentelemetry.Init(tracer, meter)
```

Today we do not have `opentelemetry.Init()` as discussed in OTEP 0005, the current equivalents are `trace.SetGlobalTracer()` and `metric.SetGlobalMeter()`.

**Comment by lizthegrey** [comment]
Broadly I'm good with that and I was looking for opentelemetry.Init() to exist in the future anyways. My one concern is being able to incrementally construct more than one exporter without passing all of the config options into one line, but we can just construct the exporter params individually then feed them to the tracer.

I still feel it's confusing friction to require someone both to import sdktrace and apitrace in one app but that's a larger usability issue we can tackle down the road by moving the tracer instantiation code perhaps to another package not also named "trace"

With that agreed upon as the longer term plan are you okay with merging this as is so we have consistency between exporters for the short term with the understanding we'll delete and replace with the new methods ASAP?

**Comment by lizthegrey** [comment]
Wait, there's another minor problem: error handling. It's possible that NewExporter() might fail for network exporters, so we need to check that error condition, and not pass that nil exporter into the arguments list at minimum, and possibly bail rather than continue startup depending upon the client's requirements to have telemetry be a soft or hard dependency...

**Comment by jmacd** [comment]
Yes, I think the main function should check all the error conditions. (It's not clear why `stdout.NewExporter` would ever return an error, on that topic.) 

I believe it will be only the `main` module that imports the SDK package and the API package. See also #216.

There are lingering questions, to me, about whether there should be __standard__ options for configuring SDKs that are used by more than one SDK.  That would imply a new package, as you say, where all the common options for setting samplers, processors, and exporters reside.

**Comment by lizthegrey** [comment]
> Yes, I think the main function should check all the error conditions. (It's not clear why `stdout.NewExporter` would ever return an error, on that topic.)
It probably won't ever, but we should be standard that the Exporter convention is to return `(trace.Exporter, error)` even if `error` is `nil` in practice most of the time.

> I believe it will be only the `main` module that imports the SDK package and the API package. See also #216.
+1 to #216

**Comment by lizthegrey** [comment]
@jmacd now that `NewProvider` has landed, preferences for me backing out `RegisterSimpleSpanProcessor`? Should I remove the method entirely, or should I make it use the `NewProvider` code now?

**Comment by rghetia** [comment]
@lizthegrey , I think RegisterSimpleSpanProcessor should be removed entirely. The `main` module should use NewProvider with  WithSyncer or WithBatcher option.

**Comment by lizthegrey** [comment]
Great, I'll send a pull to remove.

**Pull request merged**
