### PR TITLE
Convert XConfigure into constructors

### LINKED ISSUE #1130: Moving SpanConfig and TracerConfig to internal
Both configuring spans and tracer, there are various types and functions. It's hard for the user to determine which one they should be focused on.

For example, spans work with:
- SpanConfig
- SpanConfigure
- SpanOption

Tracers work with:
- TracerConfig
- TracerConfigure
- TracerOption

If we assume the users won't be engaging with the TracerConfig and SpanConfig directly that much, would it make sense to move SpanConfig, SpanConfigure, TracerConfig and TracerConfigure to the internal package. An example of this pattern can be found at https://godoc.org/google.golang.org/api/option where exported APIs are only options and config is an internal type.

### PR DESCRIPTION
**Pull request by rakyll**
Previously, we discussed the possibility of converting
the config types into internal ones. But due to the
cyclic dependencies it introduces, we are only
converting XConfigure into constructors and document that
XConfig types are most likely are not going to be directly
used by developers.

By naming, it makes it clear the constructors are tightly
related to the config types and not yet another way
to configure the package. It should improve the mental overhead.

Fixes #1130.

### CODE REVIEW

**Review by Aneurysm9 — APPROVED** [review]

**Comment by Aneurysm9** [comment]
Please provide a `CHANGELOG.md` entry documenting the change.

**Review by XSAM — APPROVED** [review]

**Comment by rakyll** [comment]
Added changes to the CHANGELOG, PTAL.

**Review by MrAlias — APPROVED** [review]
This naming seems to be in conflict [with the existing style guide](https://github.com/open-telemetry/opentelemetry-go/blob/master/CONTRIBUTING.md#config). However, based on what you pointed out about the grouping of this as a constructor for the related `struct` it seems like this is a better design. I think we need a follow-on issue to update to this if we all agree this is the prefered approach.

**Comment by MrAlias** [comment]
It seems like the existing `*Configure` naming also associates with the related specification in the docs:



If we decide to move to this naming pattern it seems like it would be more motivated to align with the canonical Go approach.

**Comment by rakyll** [comment]
@MrAlias, you are right. It's already aligning it -- the PR description need to be edited. I think due to the name, it looks like it's something else. If we want to go with this merge, it may improve that perception.

**Comment by rakyll** [comment]
Updated the description.

**Comment by MrAlias** [comment]
I think this is the correct direction. Opened https://github.com/open-telemetry/opentelemetry-go/issues/1160 to address the change.

**Pull request merged**
