### PR TITLE
Add "undocumented" way to be notified of dropped spans

### PR DESCRIPTION
**Pull request by joshuarubin**
It seems that #2766 has stalled out.
We're trying to get something in place without waiting on the official metrics sdk.

This is a stab at a change that does the same as the other PR, but in a way that doesn't change the exported api at all so there is no obligation for it to remain officially supported once a better approach is settled on.

Since it depends on library users using an interface they have to define and typecasting, it is still typesafe.
There are tests to ensure that it continues to work as long as needed.

We understand if merging in "hidden" functionality isn't something you'd like to do, but thought we'd try anyway.

### CODE REVIEW

**Review by Aneurysm9 — CHANGES_REQUESTED** [review]
I have seen [this movie](https://xkcd.com/1172/) before.

Even though it isn't part of the `SpanProcessor` interface, it is still an exported method on a type users can obtain which means that we're required to carry it forever.

This change also makes the `batchSpanProcessor` struct uncomparable, which is [problematic](https://github.com/open-telemetry/opentelemetry-go/blob/main/sdk/trace/provider.go#L190).

**Comment by joshuarubin** [comment]
I think that's a pretty rigid take on it being "exported". It's a private type that's only exported via interface and the interface needed to access that method isn't exported either.

Understood re: the issue of it being uncomparable. Open to suggestions there. It could be stored as a global var, but that's ugly too. I think the same issue exists if it's added to the `BatchSpanProcessorOptions` instead, right?

Anyway, I understand your position and am not going to fight too hard for this. Is there anything we can do to get what we need and make this more palatable for you?

**Comment by Aneurysm9** [comment]
> I think that's a pretty rigid take on it being "exported". It's a private type that's only exported via interface and the interface needed to access that method isn't exported either.

The Go Language Specification defines [exported identifiers](https://go.dev/ref/spec#Exported_identifiers), not me.  That definition is necessarily rigid.  I generally defer to [this analysis](https://go.googlesource.com/exp/+/master/apidiff/README.md) for definitions of [package compatibility](https://go.googlesource.com/exp/+/master/apidiff/README.md#package-compatibility) and the like.  We would fail this test if we ever removed or changed this exported method:

> Each exported name in the old package‘s scope also appears in the new package’s scope, and the object (constant, variable, function or type) denoted by that name in the old package is compatible with the object denoted by the name in the new package, and

> Understood re: the issue of it being uncomparable. Open to suggestions there. It could be stored as a global var, but that's ugly too. I think the same issue exists if it's added to the `BatchSpanProcessorOptions` instead, right?

Yes, that was an issue noted on #2766 as well.

**Comment by joshuarubin** [comment]
Given that knowing about dropped spans is critical information in production usage, do you have any suggestions?

**Comment by Aneurysm9** [comment]
A number of options were discussed on #2766 with the option to give the `BatchSpanProcessor` a `MeterProvider` and have it emit metrics regarding its performance being the ideal approach.  We cannot do that until the metrics API is stable, however, as dependencies must flow in the direction of stability and the `BatchSpanProcessor` is part of a stable module.

**Comment by joshuarubin** [comment]
That sounds great. Is there any sort of timeline, or a way we can contribute to that effort to speed things up?

**Comment by Aneurysm9** [comment]
> That sounds great. Is there any sort of timeline, or a way we can contribute to that effort to speed things up?

https://github.com/open-telemetry/opentelemetry-go/milestone/22

**Pull request closed without merging**
