### PR TITLE
Fix the "go get" command in README.md

### PR DESCRIPTION
**Pull request by mjgarton**
Since there is no buildable source in the top level directory, running
`go get -u go.opentelemetry.io/otel` says "Can't load package".

Fix this, by instead using `go.opentelemetry.io/otel/...`

### CODE REVIEW

**Comment by lizthegrey** [comment]
Please sign CLA.

**Comment by mjgarton** [comment]
I signed it.

**Comment by lizthegrey** [comment]
as per https://github.com/open-telemetry/opentelemetry-go/issues/371 holding off on merging this, there isn't consensus (perhaps we should default to importing `api` but not `sdk`, for instance.

**Comment by rghetia** [comment]
Addressed in #505

**Pull request closed without merging**
