### PR TITLE
allow otlp clients to use existing grpc connection

### PR DESCRIPTION
**Pull request by tonistiigi**
This is needed when the same endpoint is already reused for other gRPC services.

Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>

### CODE REVIEW

**Comment by Aneurysm9** [comment]
How does this interact with the reconnection logic?  It looks like this would prevent a reconnection attempt from ever happening.

**Comment by tonistiigi** [comment]
> How does this interact with the reconnection logic? It looks like this would prevent a reconnection attempt from ever happening.

Iiuc https://github.com/open-telemetry/opentelemetry-go/blob/3be9813d56ff53aede1f2c77c54fd5bd3e53dcc7/exporters/otlp/otlptrace/internal/connection/connection.go#L158 `disconnectedCh` only gets called on `SetStateDisconnected` that ~only~ gets called if `c.connect` returns an error. Only way `c.connect` returns and error is if `c. dialToCollector` returns an error. With this change `dialToCollector` can not return error if `GRPCConn` is set. Another case is that `SetStateDisconnected` is manually called on `Export` error. Imho this is not correct as gRPC internally redials on connection drop but if we are not going to make changes in that atm. how about I change `*grpc.ClientConn` to `GRPCDialer func(target string, opts ...DialOption) (*ClientConn, error)`. Then this function defines when new grpc conns are created or can choose to ignore it and let grpc library handle reconnection.

**Comment by paivagustavo** [comment]
I do have a feeling that we have an unnecessary complexity with our reconnection logic implementation. As @tonistiigi pointed out, GPRC already handles reconnection. 

I'm curious to know why did we need to implement that in the first place, I would love to simply delete that reconnection logic if we don't actually need. That would be a good thing to do before accepting the proposed changes of this PR.

**Comment by Aneurysm9** [comment]
It looks like the [background reconnection logic](https://github.com/open-telemetry/opentelemetry-go/blame/v0.14.0/exporters/otlp/otlp.go#L134) has been there since the exporter was initially created in #497.  I'm honestly not sure whether it is required or not.  Do we have an easy way of figuring it out, one way or the other?

**Comment by MadVikingGod** [comment]
How does this interact with a connection that has been instrumented?  

I haven't tested it but it looks like we are enabling a path for loops to happen.  I understand that this could be fixed by a future OTEP, but I would think it might be wise to wait to add this feature when those loops are preventable.

**Comment by tonistiigi** [comment]
> when those loops are preventable.

What do you mean by that?

As the caller passes the conn, it is its responsibility to pass a correct one that avoids the loops. In the code where I'm using it, I am actually tracing the grpc connection itself. So I made sure to create it with an interceptor filter. Do you mean that this should be just simpler (eg. in opentracing there is a builtin method but in opentelemetry it needs to be done manually)? If that is the case I agree that otel should have a filter method as well and willing to contribute it but I don't think it is blocking.

**Review by MrAlias — APPROVED** [review]

**Comment by MrAlias** [comment]
> It looks like the [background reconnection logic](https://github.com/open-telemetry/opentelemetry-go/blame/v0.14.0/exporters/otlp/otlp.go#L134) has been there since the exporter was initially created in #497. I'm honestly not sure whether it is required or not. Do we have an easy way of figuring it out, one way or the other?

I'm pretty sure this was inherited from OpenCensus: https://github.com/census-ecosystem/opencensus-go-exporter-ocagent/blob/master/connection.go

> I do have a feeling that we have an unnecessary complexity with our reconnection logic implementation. As @tonistiigi pointed out, GPRC already handles reconnection.
> 
> I'm curious to know why did we need to implement that in the first place, I would love to simply delete that reconnection logic if we don't actually need. That would be a good thing to do before accepting the proposed changes of this PR.

I'm guessing we might have inherited the code from a time before gRPC handled this. I agree we should validate and remove it if is not used.

**Review by pellared — APPROVED** [review]
My first impression is that the existing reconnection logic is not needed (and can be even harmful). _I have not looked into the details._

Thanks to this PR the user can use things like:
1. retry middleware from https://github.com/grpc-ecosystem/go-grpc-middleware
2. "vanilla" gRPC Go retry feature: https://github.com/grpc/grpc-go/tree/master/examples/features/retry

**Comment by thaJeztah** [comment]
@tonistiigi needs a rebase (again)

@pellared @Aneurysm9 @MrAlias anything left to do on this one (besides the rebase)? Trying to get rid of (what we hoped to be a short-lived) fork in BuildKit; https://github.com/moby/buildkit/blob/d211b5a50553ad12b7c6c8012e9212ce033beda6/go.mod

**Pull request merged**
