### PR TITLE
Move metric code to a separate package

### PR DESCRIPTION
**Pull request by krnowak**
Part of #1303

### CODE REVIEW

**Comment by krnowak** [comment]
I'm not really sure if the changelog entry is correct. Was the metrictest package merged into metric package or it rather went into oteltest package?

**Comment by MrAlias** [comment]
> I'm not really sure if the changelog entry is correct. Was the metrictest package merged into metric package or it rather went into oteltest package?

It was merged into the oteltest package. I didn't include that package in this encapsulation, but am not sure the best course of action there. It felt appropriate for a separate issue.

**Review by MrAlias — APPROVED** [review]

**Comment by krnowak** [comment]
> > I'm not really sure if the changelog entry is correct. Was the metrictest package merged into metric package or it rather went into oteltest package?
> 
> It was merged into the oteltest package.

Alright, I'll amend the changelog to mention this.

> I didn't include that package in this encapsulation, but am not sure the best course of action there. It felt appropriate for a separate issue.

`oteltest` seems to be a part of the encapsulation proposal, and it basically stays as is. Not sure if there is any action required.

**Comment by MrAlias** [comment]
> `oteltest` seems to be a part of the encapsulation proposal, and it basically stays as is. Not sure if there is any action required.

I'm going to add this to tomorrows SIG meeting agenda. I'm interested to hear if others have suggestions.

**Review by jmacd — APPROVED** [review]

**Review by XSAM — APPROVED** [review]

**Pull request merged**
