### PR TITLE
refactor: use Key's Defined method

### PR DESCRIPTION
**Pull request by 1046102779**

### CODE REVIEW

**Comment by dmathieu** [comment]
You're marking this as an optimization (in your PR title). How is that so?
It seems the only reason for this change would be to reuse the key's validation, or for readability of the code.

**Comment by 1046102779** [comment]
> You're marking this as an optimization (in your PR title). How is that so? It seems the only reason for this change would be to reuse the key's validation, or for readability of the code.

Yes. Use existing method to maintain functional consistency. 

Is it  necessary for this change?

**Comment by pellared** [comment]
@1046102779 The title is misleading. I suggest changing to `refactor: use Key's Defined method`

**Comment by 1046102779** [comment]
> @1046102779 The title is misleading. I suggest changing to `refactor: use Key's Defined method`
> 
> PS. I think the change would rather decrease the performance than improve it 😄 for performance-related PRs you should include benchmarks

ok , I run the benchmark for the change.

**Review by pellared — APPROVED** [review]

**Review by Aneurysm9 — APPROVED** [review]

**Pull request merged**
