### PR TITLE
Add support for Go 1.19

### PR DESCRIPTION
**Pull request by MrAlias**

### CODE REVIEW

**Review by dashpole — APPROVED** [review]

**Review by XSAM — APPROVED** [review]
lgtm

**Review by jmacd — APPROVED** [review]

**Review by MadVikingGod — APPROVED** [review]
LGTM.

Just a recap of the [last discussion](https://github.com/open-telemetry/opentelemetry-go/issues/2918) we had about timing of this.

1. This release will add 1.19
2. The next release after will drop 1.17

**Comment by MrAlias** [comment]
> 1. This release will add 1.19
> 2. The next release after will drop 1.17

Ah, yes, I believe this is correct. I think we need to update our README to remove the time constrains we added [here](https://github.com/open-telemetry/opentelemetry-go#compatibility):

> - The first release or one month, which ever is sooner, will add build steps for the new go version.
> - The first release after three months will remove support for the oldest go version.

I'll open a PR to do so.

**Comment by MadVikingGod** [comment]
TODO Add the go 1.19 tests to the required checks.

**Pull request merged**
