### PR TITLE
readability: improve code readability

### PR DESCRIPTION
**Pull request by hitzhangjie**
- put type declartion and its methods together
- fix wrong parameter name

### CODE REVIEW

**Review by dashpole — APPROVED** [review]

**Comment by jmacd** [comment]
I approve based on my "reviewer is always right" philosophy, though I have a personal preference for leaving types at the top of a source file. :shrug:

**Review by jmacd — APPROVED** [review]

**Review by XSAM — APPROVED** [review]
> I approve based on my "reviewer is always right" philosophy, though I have a personal preference for leaving types at the top of a source file. 🤷

I personally prefer leaving declaration and its methods together. 😆

**Review by pellared — APPROVED** [review]

**Comment by Aneurysm9** [comment]
@hitzhangjie can you please merge `origin/main` into this branch so that we can merge it?  Thanks.

**Review by MadVikingGod — APPROVED** [review]
Just a reminder that to get this merged it needs to be updated with main. It is currently based on an old version.

**Comment by MrAlias** [comment]
Closing as this looks abandoned. @hitzhangjie if you would like to still merge these changes please reopen this after merging `main` into your branch.

**Pull request closed without merging**
