### PR TITLE
Revert Logger.IsEnabled to not require Record

### PR DESCRIPTION
**Pull request by bogdandrutu**
Resolves https://github.com/open-telemetry/opentelemetry-go/issues/5769

### CODE REVIEW

**Review by pellared — CHANGES_REQUESTED** [review]
Adding options would decrease the performance (by adding heap allocations) on a path where users expect high-performance.

Reference: https://github.com/open-telemetry/opentelemetry-go/blob/main/log/DESIGN.md#options-as-parameter-to-loggeremit

**Comment by pellared** [comment]
How about changing the `Enabled` to accept a simple struct named e.g. `EnabledParams` with getters and setters in order to avoid heap allocations?

Can also not rename the method (from `Enabled` to `IsEnabled`) in the same PR?

**Comment by bogdandrutu** [comment]
> Adding options would decrease the performance (by adding heap allocations) on a path where users expect high-performance.

> Reference: https://github.com/open-telemetry/opentelemetry-go/blob/main/log/DESIGN.md#options-as-parameter-to-loggeremit

Sure, but then we must have it extensible, so we need a way to be able to add more params. A different pattern that avoids allocations is to have a struct "Settings/Config" instead, but I followed your patterns.

**Comment by pellared** [comment]
> A different pattern that avoids allocations is to have a struct "Settings/Config" instead [...]

This seems acceptable to me (as noted in https://github.com/open-telemetry/opentelemetry-go/pull/5770#issuecomment-2327444064)

**Comment by bogdandrutu** [comment]
>EDIT: At minimum, we need to be able to set the log record severity level. Needed for: https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/processors/minsev/minsev.go

I would prefer this in specs before adding support to be honest.

**Comment by pellared** [comment]
> I would prefer this in specs before adding support to be honest.

I agree. What do you think with something like the following?

> The API SHOULD accept the same set of parameters as [Emit a LogRecord](#emit-a-logrecord):
>
> - Timestamp
> - Observed Timestamp
> - The Context associated with the `LogRecord`. The API
>   MAY implicitly use the current Context as a default
>   behavior.
> - Severity Number
> - Severity Text
> - Body
> - Attributes
>
> Other parameters can be added in the future, therefore, the API MUST be
structured in a way for parameters to be added.
>
> All parameters are optional. It MUST be possible to distinguish between
> an unset parameter value from a parameter value set explicitly to a default value of given type.

**Comment by MrAlias** [comment]
> > EDIT: At minimum, we need to be able to set the log record severity level. Needed for: https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/processors/minsev/minsev.go
> 
> I would prefer this in specs before adding support to be honest.

This was removed from the specification based on the feedback of the spec SIG during a meeting: https://github.com/open-telemetry/opentelemetry-specification/pull/4020/commits/19ade6db74d62bd139f3e81f8497342f2da393c4

**Comment by MrAlias** [comment]
> Are you able to find the SIG meeting date so that I can watch the recording?

My best guess would be May 7th.

**Comment by bogdandrutu** [comment]
>The fact that something can be added in future does not mean that it can accept any parameters right now.

Correct, that is why I did this PR.

**Comment by pellared** [comment]
> This was removed from the specification based on the feedback of the spec SIG during a meeting: https://github.com/open-telemetry/opentelemetry-specification/commit/19ade6db74d62bd139f3e81f8497342f2da393c4

From my understanding it was removed mostly because @jack-berg just wanted to decrease the scope of the PR and postpone the discussions around parameters. From transcript (a little cleaned up):

> We're essentially trying to foresee with this is like what arguments will need to be present, for this is enabled method. Is it just severity? Is it no arguments at all? Are we going to want to evolve the arguments over time.
I don't have the answers to those questions.
I wonder if we can do something like, you know, just to progress this because there's there's kind of like there's some chicken in the eggs problems here. It's like, you know, we want to get this merged. 
[...]
This API should be structured so that the arguments you pass to it are are evolvable. So we can like, you know, we can leave ourselves room to evolve it from multiple standpoints. There's explicit text that says that the arguments can change, and 2, it's experimental.
I think I'd feel good about it then, because then we could, like, you know, get this valuable thing in now [...]

**Comment by pellared** [comment]
Issue was solved in https://github.com/open-telemetry/opentelemetry-specification/pull/4203

**Pull request closed without merging**
