### PR TITLE
Update go.mod for stackdriver exporter

### PR DESCRIPTION
**Pull request by lizthegrey**
Resolves failure to build due to slew between otel-go module's protos and otel-go/stackdriver module. We were using the new behavior from https://github.com/open-telemetry/opentelemetry-go/pull/256 but not the correct build hash to reflect it.

FYI @ymotongpoo

### CODE REVIEW

**Comment by krnowak** [comment]
CI failed:

```
Working tree is not clean, did you forget to run "make precommit"?

On branch pull/267
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   example/http-stackdriver/go.mod

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by lizthegrey** [comment]
I... what? I submitted this directly on github. I'll clean this up in my normal dev environment in a second then :)

sorry about that, I assumed Github would give me a clean tree...

**Comment by lizthegrey** [comment]
PTAL

**Comment by rghetia** [comment]
trigger CLA

**Pull request merged**
