### PR TITLE
Exponential histogram aggregator & export support

### PR DESCRIPTION
**Pull request by jmacd**
This implementation of the OTLP v0.11 exponential histogram provides an aggregator for calculating ExponentialHistogramDataPoint values from individual measurements. There are two configurable parameters:

1. the maximum size: unless range limits are set, the implementation auto-scales to fit the observed values into the available buckets
2. the range limits (optional): when configured, the scale is fixed to allow the full range of values at the best resolution possible given the maximum size.

This implementation includes a README documenting the implementation strategy and several points about the treatment subnormal values. This is meant to be used as a reference implementation, for producing exponential histograms according to the [OTel data model](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/datamodel.md#exponentialhistogram). 

Although this type is not specified in the currently-frozen Metrics SDK specification, it has been specified in the data model. Merging this code now will allow this implementation to be used both for experimental purposes (e.g., vendors supporting OTLP v0.11) and inside the OpenTelemetry collector (e.g., https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6666).

### CODE REVIEW

**Comment by jmacd** [comment]
@yzhuge and @oertl
Please take a look at this implementation, and most of all **THANK YOU** both for your help with and research into this histogram, its data model, and its protocol. The implementation here was inspired by both of yours. I've written up the design in the README.

**Comment by yzhuge** [comment]
I only had a cursory review on this one. And I am not fluent in Go. Overall looks good. A few minor comments:

- You may want to document that underflow/overflow errors will be returned if the "update" value is beyond the configured min/max limit.

- exponential.go    L86: // the less than equal bucket count for the pre-determined boundaries.
  Is "less than" still true? or should this be "greater than"

- exponential.go    
  L309: // Count implements aggregation.**Sum**.
  L310: func (a *Aggregator) **Count**() (uint64, error) {
Comment/code mismatch?

**Comment by jmacd** [comment]
:cry: 
```
golangci-lint in ./exporters/otlp/otlpmetric
ERRO [runner] Panic: nilness: package "runtime" (isInitialPkg: false, needAnalyzeSource: true): runtime error: index out of range [1] with length 1: goroutine 5404 [running]:
runtime/debug.Stack()
	/usr/local/Cellar/go/1.17.2/libexec/src/runtime/debug/stack.go:24 +0x65
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func1()
	/Users/jmacd/src/lightstep/go/pkg/mod/github.com/golangci/golangci-lint@v1.43.0/pkg/golinters/goanalysis/runner_action.go:101 +0x155
panic({0x4bb12e0, 0xc0008ad188})
	/usr/local/Cellar/go/1.17.2/libexec/src/runtime/panic.go:1038 +0x215
honnef.co/go/tools/analysis/facts/nilness.impl.func1({0x4e583c8, 0xc004927320})
	/Users/jmacd/src/lightstep/go/pkg/mod/honnef.co/go/tools@v0.2.1/analysis/facts/nilness/nilness.go:153 +0xddb
honnef.co/go/tools/analysis/facts/nilness.impl.func1({0x4e58ab0, 0xc00475abd0})
	/Users/jmacd/src/lightstep/go/pkg/mod/honnef.co/go/tools@v0.2.1/analysis/facts/nilness/nilness.go:140 +0xe7f
honnef.co/go/tools/analysis/facts/nilness.impl(0xc006ee25b0, 0xc006744a20, 0xc005462cd0)
	/Users/jmacd/src/lightstep/go/pkg/mod/honnef.co/go/tools@v0.2.1/analysis/facts/nilness/nilness.go:232 +0x397
honnef.co/go/tools/analysis/facts/nilness.run(0xc006ee25b0)
	/Users/jmacd/src/lightstep/go/pkg/mod/honnef.co/go/tools@v0.2.1/analysis/facts/nilness/nilness.go:66 +0x126
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyze(0xc002a12c80)
	/Users/jmacd/src/lightstep/go/pkg/mod/github.com/golangci/golangci-lint@v1.43.0/pkg/golinters/goanalysis/runner_action.go:187 +0x9c4
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func2()
	/Users/jmacd/src/lightstep/go/pkg/mod/github.com/golangci/golangci-lint@v1.43.0/pkg/golinters/goanalysis/runner_action.go:105 +0x1d
github.com/golangci/golangci-lint/pkg/timeutils.(*Stopwatch).TrackStage(0xc001600000, {0x4c14054, 0x7}, 0xc00052df60)
	/Users/jmacd/src/lightstep/go/pkg/mod/github.com/golangci/golangci-lint@v1.43.0/pkg/timeutils/stopwatch.go:111 +0x4a
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe(0xc002a12c80)
	/Users/jmacd/src/lightstep/go/pkg/mod/github.com/golangci/golangci-lint@v1.43.0/pkg/golinters/goanalysis/runner_action.go:104 +0x85
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze.func2(0xc00052dea0)
	/Users/jmacd/src/lightstep/go/pkg/mod/github.com/golangci/golangci-lint@v1.43.0/pkg/golinters/goanalysis/runner_loadingpackage.go:80 +0x67
created by github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze
	/Users/jmacd/src/lightstep/go/pkg/mod/github.com/golangci/golangci-lint@v1.43.0/pkg/golinters/goanalysis/runner_loadingpackage.go:75 +0x1fd 
WARN [runner] Can't run linter goanalysis_metalinter: goanalysis_metalinter: nilness: package "runtime" (isInitialPkg: false, needAnalyzeSource: true): runtime error: index out of range [1] with length 1 
make: *** [lint] Error 7
```

**Comment by jmacd** [comment]
@MrAlias and potential reviewers. I have a proposal to split this PR into two parts. The first part will introduce only the mapping functions. In the present PR I have these in an internal package, but these are the functions needed in the OTel collector to support printing exponential histogram data points. If you agree to, I propose to close this PR and resubmit it as two: (1) public mapping functions, (2) the new aggregator.

**Comment by jmacd** [comment]
(Closing this anyway; I found a way to simplify the logarithm implementation somewhat.)

**Comment by jmacd** [comment]
@MrAlias Re: https://github.com/open-telemetry/opentelemetry-specification/pull/2252

The "somewhat simplified" change I have in mind is hinted at in the datamodel example there -- in the present state of this PR I have prebuilt a table of histogram settings for scales -10 through 20; the calculation is trivial and leads to no allocations at runtime, but I was using a separate program to generate the table as code. The reason this was helpful is that it (a) the largest finite bucket boundary is somewhat difficult to compute, (b) if you're pregenerating code, the value can be calculated via `math/big`. 

I will change the code to calculate and cache these constants cached, not build them in.
For the largest finite bucket, instead of storing a value calculated via `math/big` I'll use the alternate formula given in https://github.com/open-telemetry/opentelemetry-specification/pull/2252.

**Comment by jmacd** [comment]
I will re-open this PR after #2502, potentially.

**Comment by sk-** [comment]
@jmacd Now that #2502 was merged do you plan on revisiting this PR?

**Comment by jmacd** [comment]
Yes, after https://github.com/open-telemetry/opentelemetry-specification/pull/2252, which will merge in the next few days.

**Comment by BrandonArp** [comment]
@jmacd how are things looking here? https://github.com/open-telemetry/opentelemetry-specification/pull/2252 looks like it got merged and I'm excited to be able to use exponential histograms

**Pull request closed without merging**
