### PR TITLE
Allow multi-instrument callbacks to be unregistered

### PR DESCRIPTION
**Pull request by MrAlias**
Resolves https://github.com/open-telemetry/opentelemetry-go/issues/3452

- Add a new `Registration` type to the metric API and have the `Meter`'s `RegisterCallback` method return one.
- Update implementations to support `Registration`s.

### CODE REVIEW

**Review by MadVikingGod — COMMENTED** [review]
Is there a test showing that the callback isn't called in collects after `Unregister()`?

**Comment by MrAlias** [comment]
> Is there a test showing that the callback isn't called in collects after `Unregister()`?

[There is one for the global implementation](https://github.com/open-telemetry/opentelemetry-go/blob/b2c4778fca4ab77b8a81003e3540524ce43a4214/metric/internal/global/meter_test.go#L291-L337). I'll add one for the SDK implementation.

**Comment by MrAlias** [comment]
> > Is there a test showing that the callback isn't called in collects after `Unregister()`?
> 
> [There is one for the global implementation](https://github.com/open-telemetry/opentelemetry-go/blob/b2c4778fca4ab77b8a81003e3540524ce43a4214/metric/internal/global/meter_test.go#L291-L337). I'll add one for the SDK implementation.

Added in c56c1409cf4b968a2933c4d6a9f50a2bef9096cc

**Review by dashpole — APPROVED** [review]

**Review by jmacd — APPROVED** [review]
Cool!

**Pull request merged**
