### PR TITLE
Add docs on when reviews should be cleared

### LINKED ISSUE #1555: Add documentation on when PR reviews should be cleared
Instead of automating the dismissal of PR reviews when changes are made to an approved PR, which can include changes like merging main into the branch, we need to get into the practice of manually clearing reviews when substantive changes are made to the PR.

To start with at least, we need to document what is expected in the CONTRIBUTING documentation.

### PR DESCRIPTION
**Pull request by MrAlias**
Resolves #1555

### CODE REVIEW

**Review by Aneurysm9 — APPROVED** [review]

**Comment by punya** [comment]
I learned today that PR authors who aren't maintainers don't have the ability to dismiss reviews 😞  At most, they can re-request review (but any existing approvals still stand).

**Review by punya — CHANGES_REQUESTED** [review]
I learned today that PR authors who aren't maintainers don't have the ability to dismiss reviews 😞  At most, they can re-request review (but any existing approvals still stand).

**Review by XSAM — APPROVED** [review]

**Comment by Aneurysm9** [comment]
> I learned today that PR authors who aren't maintainers don't have the ability to dismiss reviews 😞 At most, they can re-request review (but any existing approvals still stand).

Hmmm, does that mean we need a different approach?  Do approvers have the ability to dismiss reviews or is it only maintainers?

**Comment by MrAlias** [comment]
> Hmmm, does that mean we need a different approach? Do approvers have the ability to dismiss reviews or is it only maintainers?

It looks like we can explicitly set who can dismiss reviews for the repo:



Should we add OpenTelemetry members to this list? Or restrict it to go-approvers?

Also, I want to verify the statement that I made in the SIG a while ago: that the branch protection rule "Dismiss stale pull request approvals when new commits are pushed" will clear merges from the main branch. I remember this being the case when I originally tried it out, but the description of that setting ("New reviewable commits pushed to a matching branch will dismiss pull request review approvals.") makes me question this might have changed.

**Comment by MrAlias** [comment]
I've updated to allowing the go-approvers to dismiss reviews. I could not figure out how to have the interface allow all members of the org to dismiss reviews (it would not auto-complete a selection).

**Pull request merged**
