### PR TITLE
API: Convert Event interface to concrete type

### PR DESCRIPTION
**Pull request by agneum**
Resolve https://github.com/open-telemetry/opentelemetry-go/issues/76
Please check if everything works as expected.

### CODE REVIEW

**Comment by rghetia** [comment]
@agneum please sign CLA.

**Comment by rghetia** [comment]
@agneum the Event interface that we want to convert to concrete type is [this](https://github.com/open-telemetry/opentelemetry-go/blob/fafb3daf1efc977851352db36664a1f9ea6edfa3/api/event/event.go#L22).

**Comment by agneum** [comment]
> @agneum please sign CLA.
I've already signed it

> @agneum the Event interface that we want to convert to concrete type is [this](https://github.com/open-telemetry/opentelemetry-go/blob/fafb3daf1efc977851352db36664a1f9ea6edfa3/api/event/event.go#L22).
Got it. I'll fix

**Comment by agneum** [comment]
I signed it

**Comment by agneum** [comment]
> @agneum please sign CLA.
It's a bit strange. I signed CLA and got confirmation. However the check doesn't pass. Then I submitted a support request. 
I hope we'll resolve the agreement issue soon.

I changed the Event interface to the api event. Does the fix look better?

**Comment by rghetia** [comment]
> It's a bit strange. I signed CLA and got confirmation. However the check doesn't pass. Then I submitted a support request.
> I hope we'll resolve the agreement issue soon.

Did you use the same email for signing as you do for authoring code?

**Comment by agneum** [comment]
> > It's a bit strange. I signed CLA and got confirmation. However the check doesn't pass. Then I submitted a support request.
> > I hope we'll resolve the agreement issue soon.
> 
> Did you use the same email for signing as you do for authoring code?

Yes, I did. It's my primary email address on Github.

**Comment by rghetia** [comment]
> I changed the Event interface to the api event. Does the fix look better?

Sorry for not clarifying properly. Currently [event.Event](https://github.com/open-telemetry/opentelemetry-go/blob/fafb3daf1efc977851352db36664a1f9ea6edfa3/api/event/event.go#L22) is an interface. We want to change that to a concrete type.

```go

type Event struct {
	message string
	attr    []core.KeyValue
}
func (e *Event) Message() string {
	return e.message
}
...
```
leave the evictedqueue as is. It is generic queue to store any type of values.

**Comment by agneum** [comment]
> Sorry for not clarifying properly. Currently event.Event is an interface. We want to change that to a concrete type.

I'm sorry, my mistake.
I'll create a new PR.

By the way, it turns out that the event is not needed in the basetypes.go right now, right?

**Comment by agneum** [comment]
There is an actual PR: https://github.com/open-telemetry/opentelemetry-go/pull/106

**Pull request closed without merging**
