### PR TITLE
[schema] Use type aliases instead of type definitions

### PR DESCRIPTION
**Pull request by MovieStoreGuy**
## Context 

While trying to implemented the schema processor within the collector to share code, it required having generic constructors since these types create a new type definition instead of using a type alias which would remove the need for a generic receiver.

See: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17020#discussion_r1188769773  for example.

## Changes

I've simply just updated the definitions to be aliases which should be fine due to the fact that no additional methods were added to those types.

### CODE REVIEW

**Review by pellared — CHANGES_REQUESTED** [review]
This is a breaking change.

PS. AFAIK type aliases were introduced to support gradual code changes while moving a type between packages during large-scale refactoring.

**Comment by MovieStoreGuy** [comment]
> This is a breaking change.

I am not convinced this is breaking change since any usage of these would continue to work due to the lack of method receivers being applied to these types.  Assignment and type validation would still continue to work. Anything that would extend these types would also have no impact.

The type comments even lead me to believe that the types _should_ be aliases instead of new type definitions.

I am not sure what else I am missing that this would be considered a breaking change, do you have an example?

> PS. AFAIK type aliases were introduced to support gradual code changes while moving a type between packages during large-scale refactoring.

That isn't its only usage,  considering that `byte` is an alias for `uint8` and `rune` is an alias for `int32` as defined by the golang language spec.

Having a look at @tigrannajaryan original PR, I believe the intent was to have aliased types so when reviewing the AST code it was clear what is being represented there as seen by:

- https://github.com/open-telemetry/opentelemetry-go/blob/main/schema/v1.0/ast/spans.go#L39
- https://github.com/open-telemetry/opentelemetry-go/blob/main/schema/v1.0/ast/spans.go#L57:L58
- https://github.com/open-telemetry/opentelemetry-go/blob/main/schema/v1.0/ast/metrics.go#L27
- https://github.com/open-telemetry/opentelemetry-go/blob/main/schema/v1.0/ast/metrics.go#L34

**Comment by MovieStoreGuy** [comment]
I've spent some time trying to see if I can help put a finger on why these types feel out of place, and it is the compile time type assertion with typedefs that are making it cumbersome on my behalf. 

The portions that I am finding rough edges is the `[]MetricName`, `[]SpanName`, and `[]EventName` since you can't simply type cast these to `[]string` without casting each to a string into a new array. The same is also true where they have been used within maps.

This means trying to write the components in the schema processor that I've generalised these attribute checks on signal to be a `ConditionalAttributeSet`, either means I would need to do:

1. Write an optional func to convert from AST type to generic conditional type
2. Do some casting of `any` to the expected types
3. Have a constructor that uses a generic receiver `T interface{ ~string}` that doesn't require casting

1 is doable but requires a lot of duplicate code just using different types, 2 sounds like a nightmare just thinking of it, and 3 is my current preferred option (if we were to keep the type defs) since that requires the least amount of code and fairly simple to ensure correctness (and compile time checking on type constraints). 

An alternative that would help with trying to consume these values in the schema processor would provide a means to consume them as the primitive type, would that be a better approach to take here?
Not completely sure on what the implementation would look like here but I imagine we can make these types internal and have more of a wrapper that make it easier to generalise some of the functionality.

**Comment by MovieStoreGuy** [comment]
Going to withdraw this PR since there is value in having the type as typedef, it just requires a bit more work on the consumers side.

**Pull request closed without merging**
