### PR TITLE
Fix interfaces doc formatting

### PR DESCRIPTION
**Pull request by pellared**
The methods should be separated by lines if there are GoDoc comments.

Side note: I tried to check all exported interface definitions.

### CODE REVIEW

**Review by XSAM — APPROVED** [review]
Do we have a linter to check this kind of formatting issue, so we can automatically check this on our CI?

**Review by dmathieu — APPROVED** [review]

**Comment by pellared** [comment]
> Do we have a linter to check this kind of formatting issue, so we can automatically check this on our CI?

Not found one so far.

**Review by dashpole — APPROVED** [review]

**Review by MrAlias — COMMENTED** [review]
What difference does this make? I don't see any formatting difference other than an added newline.

**Comment by pellared** [comment]
> What difference does this make? I don't see any formatting difference other than an added newline.

By formatting I mean only the line separating commented methods for readability. This pattern is used in other places in OTel Go as well as in the Go standard library.

**Comment by pellared** [comment]
@MrAlias, are you OK to have this PR merged?

**Review by hanyuancheung — APPROVED** [review]

**Pull request merged**
