### PR TITLE
Rename internal_logging*.go to logging.go in `internal/global`

### PR DESCRIPTION
**Pull request by MrAlias**
The file is already within the `internal` package. Simplify the name to only "logging" so devs can find it easier.

### CODE REVIEW

**Review by dashpole — APPROVED** [review]

**Review by pellared — CHANGES_REQUESTED** [review]
The current name is good. We will  most probably add `log.go` or `logger.go` for to set/access the global logger provider and logger (the one from OTel Logs API). Current name says that it is internal logging and helps differentiating.

**Comment by pellared** [comment]
I will take another look on Monday

**Comment by pellared** [comment]
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/bridge-api.md#loggerprovider

**Comment by MrAlias** [comment]
Why not address naming when we are adding the global logging? I seems like a better time to discus given there is no conflict now and there will be more naming changes we are going to need to look at.

**Comment by pellared** [comment]
I prefer the file current name. For me the word "internal" has a different context in file name and import path. In import path it says that it is an internal package (language specific term) in file name it is saying that it is internal logging ("domain" name, it is a logger that is used internally in this repository).

**Review by hanyuancheung — APPROVED** [review]

**Pull request closed without merging**
