### PR TITLE
Add logs to dice example

### LINKED ISSUE #5058: Update dice example to use logs
Update https://opentelemetry.io/docs/languages/go/getting-started/ and https://github.com/open-telemetry/opentelemetry-go/tree/main/example/dice to use logs signal.

### PR DESCRIPTION
**Pull request by MrAlias**
Part of #5058 

Following [other langauge](https://opentelemetry.io/docs/languages/java/getting-started/) examples, use slog to log a message on the server handler. This matches other examples by using the a parameterized path to identify the player. If that player is specified, the log message will include their name.

Note, to see the parameterized path be used, you need to run this with Go 1.22+ and the following Go debug flags:

```shell
GODEBUG=httpmuxgo121=0 go run .
```

Otherwise, the application defaults to the `1.21` path behavior.

### CODE REVIEW

**Review by dashpole — COMMENTED** [review]
It doesn't seem to be using `slog`?

**Comment by MrAlias** [comment]
> It doesn't seem to be using `slog`?

This returns an `slog.Logger`:

https://github.com/open-telemetry/opentelemetry-go/pull/5349/files#diff-3dc3f1d950a9fba9c9283470a86ebd6abcac460c19de3caddbcf6743de5a7cbdR18-R22

**Review by dmathieu — APPROVED** [review]

**Review by dashpole — APPROVED** [review]

**Comment by pellared** [comment]
> Note, to see the parameterized path be used, you need to run this with Go 1.22+ and the following Go debug flags:
> 
> ```shell
> GODEBUG=httpmuxgo121=0 go run .
> ```
> 
> Otherwise, the application defaults to the `1.21` path behavior.

Would it not be better to simply bump the `go` directive in `go.mod` to `1.22`?

**Comment by MrAlias** [comment]
> > Note, to see the parameterized path be used, you need to run this with Go 1.22+ and the following Go debug flags:
> > ```shell
> > GODEBUG=httpmuxgo121=0 go run .
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Otherwise, the application defaults to the `1.21` path behavior.
> 
> Would it not be better to bump the `go` directive in `go.mod` to `1.22`?

The CI system needs Go 1.21 support still.

**Pull request merged**
