### PR TITLE
remove rSSP and rBSP code, use NewProvider instead.

### LINKED ISSUE #171: Prefer fewer globals in trace SDK initialization
Here's a typical setup for a Jaeger exporter:

```
func setupTracer() (trace.Tracer, *jaeger.Exporter, error) {
    // Register installs a new global tracer instance.
    tracer := sdk.Register()

    // Construct and register an export pipeline using the Jaeger
    // exporter and a span processor.
    exporter, err := jaeger.NewExporter(
        jaeger.Options{
            AgentEndpoint: "localhost:6831",
        },
    )
    if err != nil {
        return nil, nil, err
    }

    // A simple span processor calls through to the exporter
    // without buffering.
    ssp := sdk.NewSimpleSpanProcessor(exporter)
    sdk.RegisterSpanProcessor(ssp)

    // Use sdk.AlwaysSample sampler to send all spans.
    sdk.ApplyConfig(
        sdk.Config{
            DefaultSampler: sdk.AlwaysSample(),
        },
    )

    return tracer, exporter, nil
}
```

It feels like too many global variables are in use. We've gone to a lot of trouble to support multiple SDKs in the process, but are all SDKs expected to use the statically registered span processors? That's not what I'd expect. I'd prefer is we used only the necessary globals. In this case, we'd address the matter by constructing the exporters, then constructing the span processor, and passing them to the new SDK object along with its config.

`ApplyConfig` should be a method on the SDK (if it's dynamic) or an argument to the constructor (or both).  I made similar changes to the experimental SDK here: https://github.com/open-telemetry/opentelemetry-go/commit/a3ae50d8bce06ee8502b9bd594ef551c0f28f1a8

### PR DESCRIPTION
**Pull request by lizthegrey**
As promised in https://github.com/open-telemetry/opentelemetry-go/pull/213 remove rSSP code (and its counterpart rBSP) now that `NewProvider` is a thing.

This also requires allowing NewProvider to accept Batching parameters.

Resolves #171

### CODE REVIEW

**Comment by lizthegrey** [comment]
@rghetia and @jmacd, this cleans up technical debt you were calling to have removed.

**Comment by jmacd** [comment]
This also closes #171.

**Comment by rghetia** [comment]
@lizthegrey can you please resolve the conflicts?

**Comment by lizthegrey** [comment]
On it (but it is past midnight Zurich, so I cannot turn around another batch of changes after this)

**Comment by lizthegrey** [comment]
PTAL

**Pull request merged**
