### PR TITLE
fallback to URL.Host if Request.Host is empty

### PR DESCRIPTION
**Pull request by nelzkiddom**
The [stdlib](https://pkg.go.dev/net/http#Request) `http.Request` comments for the `Host` member variable states:

> For client requests, Host optionally overrides the Host header to send. If empty, the Request.Write method uses the value of URL.Host. Host may contain an international domain name.

The `semconv` package(s) wasn't taking `url.URL.Host` into account when `http.Request.Host` was empty.

### CODE REVIEW

**Comment by nelzkiddom** [comment]
I found this behavior in the wild, when looking at requests that were created by the `aws-sdk-go` (v1).

(Notice there's no `http.host` entry.)

Screen Shot 2022-03-07 at 16 15 01

**Review by Aneurysm9 — COMMENTED** [review]
Thanks for this!  Can you please add a `CHANGELOG.md` entry for this enhancement and apply it to the remaining `semconv` versions?

**Comment by nelzkiddom** [comment]
I can't tell which direction this should go in, as related to "versioning":
* will I be told that this is a substantive change, and would require waiting for a new `semconv/v1.7.1+` package?
* will I be told that I should make this same change in all the "previous" packages, e.g. `v1.6.1` and `v1.5.0` and `v1.4.0`?

**Comment by nelzkiddom** [comment]
As I typed that, I see now that @Aneurysm9 answered my question. I shall proceed! 🎉

**Comment by nelzkiddom** [comment]
@Aneurysm9 Made the requested changes. 👍

**Review by MrAlias — APPROVED** [review]

**Review by Aneurysm9 — APPROVED** [review]

**Pull request merged**
