### PR TITLE
release v0.1.0

### LINKED ISSUE #264: Tag a 0.1 release
👋 As we'll soon be using this package in OpenTelemetry workshops, it'd be great if we could get a 0.1 tag/github release so that workshops can have a relatively stable point-in-time to pull.

### PR DESCRIPTION
**Pull request by rghetia**
fixes #264 

After this PR is merged, I will tag the rel_0_1_x branch with the tag v0.1.0

### CODE REVIEW

**Comment by rghetia** [comment]
@austinlparker , @bogdandrutu PTAL

**Comment by austinlparker** [comment]
sgtm

**Comment by bogdandrutu** [comment]
Make sure you test this from a separate repo copy the examples and point to the tag using also one exporter

**Comment by rghetia** [comment]
> Make sure you test this from a separate repo copy the examples and point to the tag using also one exporter

sure.

**Comment by rghetia** [comment]
updated to include #286

**Comment by rghetia** [comment]
> > Make sure you test this from a separate repo copy the examples and point to the tag using also one exporter
> 
> sure.

Tested and it works!!

**Pull request merged**
