### PR TITLE
Fix typo in getting-started.md

### PR DESCRIPTION
**Pull request by jordanbertasso**
Changed "should to be" to "should be"

### CODE REVIEW

**Comment by pellared** [comment]
Are you able to sign the CLA?
More info: https://github.com/open-telemetry/community/blob/main/CONTRIBUTING.md#sign-the-cla

**Comment by jordanbertasso** [comment]
Will give it a miss for now @pellared. Feel free to make the changes yourself or I will open an issue.
Thanks!

**Comment by pellared** [comment]
I am not a native speaker. However, I feel that this whole sentence could be written in a more understandable way 😉 

Do you think it would be better:

```
The most important takeaway is that each part of your code, which does work, should be represented as a span.
```
?

**Comment by jordanbertasso** [comment]
Sure! Perhaps:

```
The most important takeaway is that each part of your code, which does some work, should be represented as a span.
```

"some work" because otherwise it sounds like the code needs to "work" in the sense that it's not broken.

**Pull request closed without merging**
