### PR TITLE
Remove usage of deprecated instrumentation.Library in favor of Scope

### PR DESCRIPTION
**Pull request by bogdandrutu**
Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>

### CODE REVIEW

**Comment by Aneurysm9** [comment]
`instrumentation.Library` is now aliased to `instrumentation.Scope`.  I'm not sure that we should be changing the types of parameters and return values in stable modules.  @open-telemetry/go-maintainers thoughts?

**Comment by dashpole** [comment]
Yeah, I don't think this would be backwards-compatible, so we will probably have to exclude uses in stable modules.  I'm in favor of it elsewhere, though

**Comment by bogdandrutu** [comment]
> Yeah, I don't think this would be backwards-compatible

How come is not? Type alias does NOT create a new type, so the 2 "types" are equal, hence the generated code is backwards compatible.

**Comment by Aneurysm9** [comment]
`interface{}` and `any` are perhaps not the best types to use to illustrate the point since they're explicitly intended to match any type and it would be impossible to break compatibility by exchanging them.  Are there any examples with concrete types that are not referenced in the language spec?

We have [previously decided](https://github.com/open-telemetry/opentelemetry-go/pull/2977#pullrequestreview-1020345392) not to make this change.  I don't see anything that changes that decision.

**Comment by bogdandrutu** [comment]
@Aneurysm9 short answer is yes, the hypothesis on which the decision was made, is invalid, see https://github.com/open-telemetry/opentelemetry-go/pull/2977#discussion_r907491454 which I am trying to prove that is not true, so the decision is wrong.

**Comment by Aneurysm9** [comment]
https://go.dev/play/p/Yt9aOTDzJCI

**Comment by Aneurysm9** [comment]
@MadVikingGod pointed out that we used an [alias rather than a typedef ](https://go.dev/play/p/TQukM9rrXQd)and [I have bad memory](https://github.com/open-telemetry/opentelemetry-go/pull/2976/files/745e0441b152c31932272cdb40081ae65037878a#diff-5b617140bf1076bd2483d1811933e4c23d87b4924c3c5d669e8604c206bac0f9).

That said, we have a goal of ensuring that dependency hell will never prevent a user from updating their instrumentation or SDK, I'd prefer to take the safer route and not change these uses in stable packages.

**Comment by bogdandrutu** [comment]
> That said, we have a goal of ensuring that dependency hell will never prevent a user from updating their instrumentation or SDK, I'd prefer to take the safer route and not change these uses in stable packages.

Unless I am missing something obvious, this will break only if only users are forcing an older SDK. But that is a problem that you have even if for example you add a new func in API, that SDK uses, you should never use that.

**Comment by MadVikingGod** [comment]
I think we may need a bit more deliberate approach to this than what has been offered here.  The metrics are fine, that is not under the 1.x stability, but I think the tracing story is different.

The two changes I would focus on are:

1. Changing `ReadOnlySpan` from `InstrumentationLibrary() instrumentation.Library` to `InstrumentationLibrary() instrumentation.Scope`.  This function is already deprecated, maybe we could do better deprecating the implementations, but I don't think it sends the right signal when the Name and the struct don't follow the rest methods.  Yes, it can be done, but it needs to be noted why it's different so that someone that was not around for the library scope transition has the context they need.
2. Changing the `tracetest.SpanStub` from `InstrumentationLibrary instrumentation.Library` to `InstrumentationLibrary instrumentation.Scope`.  For the same reasons as above, I don't think this is good to change without commenting on why. I also don't think this will be as clean as a change because we can't just add an `InstrumentationScope` field like we did with the Interface.  This would be a longer approach of creating a replacement stub, transitioning to it, and deprecating the old.

**Comment by jmacd** [comment]
I am confused as to why type aliases do not solve the problem. The same play link with an alias compiles and works as intended, right? https://go.dev/play/p/TQukM9rrXQd @Aneurysm9

**Comment by dashpole** [comment]
Thanks for explaining @jmacd. I agree that adding brief comments for when the function name and returned type differ would help clarify.

**Review by jmacd — APPROVED** [review]

**Comment by dmathieu** [comment]
With https://github.com/open-telemetry/opentelemetry-go/pull/5627 merged, this PR can be closed. Please let me know if you feel I forgot something in there.

**Pull request closed without merging**
