### PR TITLE
Change metrics API to use interfaces for Meter and BatchObserver

### PR DESCRIPTION
**Pull request by bogdandrutu**
Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>

### CODE REVIEW

**Comment by Aneurysm9** [comment]
What is the rationale for this change?

**Comment by bogdandrutu** [comment]
@Aneurysm9 great question, here are just few reasons:
1. Consistency with other languages, see Java/C#/etc.
2. The main motivation of the merge between OpenCensus and OpenTracing was exactly to give users the "big hook" which allow to replace the "entire" implementation (or as much as possible).
3. Better separation between API and implementation.
4. Keeping the public surface smaller, my intention is to actually get to a point where `sdkapi` will become an internal package to our SDK, I don't think it is needed and we can get the same result without it. The disadvantage is that alternative implementations may have to duplicate that, but I don't think that is a priority of our project to facilitate alternative implementation more than just offering them a stable API.

**Review by XSAM — APPROVED** [review]
LGTM

**Comment by bogdandrutu** [comment]
@open-telemetry/go-maintainers @open-telemetry/go-approvers if I recall correctly decision was to not go with interface but with "slim" structs, I personally don't have time to deal with that so I will close this.

**Pull request closed without merging**
