### PR TITLE
Create stdout metrics exporter

### LINKED ISSUE #2805: Add back the stdoutmetric exporter code
Blocked by the metric SDK having a working example in the new_sdk/main branch

Removed in https://github.com/open-telemetry/opentelemetry-go/pull/2802

### PR DESCRIPTION
**Pull request by MadVikingGod**
closes #2805 

This adds the first exporter back to the SDK.  This changes the stdout metrics from a custom format, I think modeled after prometheus, to just json.  We have not had any stability guarantees of the output format of the stdout exporter, as they are intended for development.

### CODE REVIEW

**Comment by MadVikingGod** [comment]
Sorry, I'll admit I didn't check the status of the issue and have just been working on this in downtime.

If you have a more flexible exporter, I'm totally ok taking that one over this.

**Comment by MrAlias** [comment]
> Sorry, I'll admit I didn't check the status of the issue and have just been working on this in downtime.
> 
> If you have a more flexible exporter, I'm totally ok taking that one over this.

Let me get a draft up in the next hour or so for you to take a look at. It will not be complete in that it does not have a full test suite, but should be good enough to get the broad strokes. I'll let you decide how we want to progress from there.

**Comment by MrAlias** [comment]
> > Sorry, I'll admit I didn't check the status of the issue and have just been working on this in downtime.
> > If you have a more flexible exporter, I'm totally ok taking that one over this.
> 
> Let me get a draft up in the next hour or so for you to take a look at. It will not be complete in that it does not have a full test suite, but should be good enough to get the broad strokes. I'll let you decide how we want to progress from there.

https://github.com/open-telemetry/opentelemetry-go/pull/3057

**Comment by MadVikingGod** [comment]
Closing, #3057 is a better direction.

**Pull request closed without merging**
