### PR TITLE
Fix infinit suffix add to counter metrics

### PR DESCRIPTION
**Pull request by ehsannm**

### CODE REVIEW

**Comment by ehsannm** [comment]
There is critical bug in Prometheus exporter, counters are growing indefinitely by adding _total to the end of the metric.

**Review by MrAlias — CHANGES_REQUESTED** [review]
This will move our implementation out of compliance with the specification: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/compatibility/prometheus_and_openmetrics.md#sums

> Monotonic Sum metric points MUST have _total added as a suffix to the metric name.

If someone already named their metric with a suffix of `_total` an additional `_total` suffix must be added still.

**Comment by ehsannm** [comment]
Thanks @MrAlias , but where should we check this infinit loop. The problem is with each new variableLabel change we get another _total added to the counter name.

# HELP qlub_pos_requests_ratio_total 
# TYPE qlub_pos_requests_ratio_total counter
qlub_pos_requests_ratio_total{code="200",country_code="ae",method="get_order",vendor="dummy"} 6
# HELP qlub_pos_requests_ratio_total_total 
# TYPE qlub_pos_requests_ratio_total_total counter
qlub_pos_requests_ratio_total_total{code="200",country_code="ae",method="get_table",vendor="dummy"} 1

**Comment by ehsannm** [comment]
ok i realized this bug is in current release tag v0.33.0 and is fixed in main branch. I close this PR. It should be fixed in next release.

**Comment by ehsannm** [comment]
BTW, i think it is critical bug, why not release a hotfix v0.33.1 for it ? @MrAlias

**Comment by jmacd** [comment]
For the next reader, the fix went in here: https://github.com/open-telemetry/opentelemetry-go/pull/3369

**Pull request closed without merging**
