### PR TITLE
Remove bound metric instruments from the API

### LINKED ISSUE #2351: Consider removing bound metric instrument support
### Problem Statement

Bound metric instruments have a large API surface area and very few members of the OTel-Go community have defended keeping them. Although the corresponding Prometheus client library has this concept, it's not clearly needed in OTel-Go at this time.

### Proposed Solution

Remove this feature until it has become part of the OTel specification. The Metrics SIG has discussed working on this after Metrics API and SDK reach 1.0.

#### Alternatives

This can be kept. I don't find myself wanting it.

#### Prior Art

See the Prometheus-Go client.

### Additional Context

The SDK structure will remain. The existing concurrency mechanism and support for "forgetting" metric instruments when configured with delta temporality means that the mechanism behind bound instruments will stay in place. It will be easy to add this feature again.

### PR DESCRIPTION
**Pull request by jmacd**
This demonstrates how much code we can remove by eliminating bound instruments. I believe this is worthwhile and I would rather focus on optimizing the code path for extracting baggage and the performance of `RecordBatch()`, not individual bound instrument APIs.

Fixes #2351

### CODE REVIEW

**Review by MadVikingGod — APPROVED** [review]
+18 -518, best kind of PRs.

I like the thrust of the code, there needs a bit of attention to lint and changelog etc.

**Review by evantorrie — APPROVED** [review]
+1

**Comment by jmacd** [comment]
> I like the thrust of the code, there needs a bit of attention to lint and changelog etc.

Thanks. I did't want to finish this PR until I had a few people agreeing I should.

**Comment by MrAlias** [comment]
> I did't want to finish this PR until I had a few people agreeing I should.

SGTM, looks like a worth while change.

**Review by bogdandrutu — APPROVED** [review]

**Comment by MrAlias** [comment]
```
golangci-lint in ./sdk/metric
benchmark_test.go:63:6: `makeManyLabels` is unused (deadcode)
func makeManyLabels(n int) [][]attribute.KeyValue {
     ^
make: *** [Makefile:139: lint] Error 1
```

**Comment by MadVikingGod** [comment]
I was asked to take over getting this PR to the finish line.  A new PR at #2399 fixes all of the outstanding issues.

**Pull request closed without merging**
