### PR TITLE
Reduce allocs on first call to WithAttributes or WithLinks for new spans/events

### PR DESCRIPTION
**Pull request by dmathieu**
Most of the time, folks are likely to only call `WithAttributes` or `WithLinks` only once, in which case, calling `append()` is twice slower, and creates one allocation.

On the first call to either those options, this change will now use directly the passed data, so no append needs to happen.

The gobench below is running with the commits from #5566.

```
pkg: go.opentelemetry.io/otel/trace
                                                         │  bench-main  │            bench-branch             │
                                                         │    sec/op    │   sec/op     vs base                │
NewSpanStartConfig/with_no_options-10                       4.292n ± 1%   4.281n ± 1%        ~ (p=0.315 n=10)
NewSpanStartConfig/with_attributes-10                       45.22n ± 1%   26.70n ± 2%  -40.94% (p=0.000 n=10)
NewSpanStartConfig/with_attributes_set_multiple_times-10   103.20n ± 2%   80.00n ± 1%  -22.48% (p=0.000 n=10)
NewSpanStartConfig/with_a_timestamp-10                      21.37n ± 1%   21.36n ± 1%        ~ (p=0.925 n=10)
NewSpanStartConfig/with_links-10                            60.28n ± 3%   27.75n ± 0%  -53.97% (p=0.000 n=10)
NewSpanStartConfig/with_links_set_multiple_times-10         141.9n ± 5%   105.9n ± 1%  -25.37% (p=0.000 n=10)
NewSpanStartConfig/with_new_root-10                         27.51n ± 2%   27.64n ± 2%        ~ (p=0.424 n=10)
NewSpanStartConfig/with_span_kind-10                        27.65n ± 2%   27.68n ± 1%        ~ (p=0.617 n=10)
geomean                                                     35.94n        28.53n       -20.62%

                                                         │  bench-main  │              bench-branch               │
                                                         │     B/op     │    B/op     vs base                     │
NewSpanStartConfig/with_no_options-10                      0.000 ± 0%     0.000 ± 0%         ~ (p=1.000 n=10) ¹
NewSpanStartConfig/with_attributes-10                      64.00 ± 0%      0.00 ± 0%  -100.00% (p=0.000 n=10)
NewSpanStartConfig/with_attributes_set_multiple_times-10   192.0 ± 0%     128.0 ± 0%   -33.33% (p=0.000 n=10)
NewSpanStartConfig/with_a_timestamp-10                     0.000 ± 0%     0.000 ± 0%         ~ (p=1.000 n=10) ¹
NewSpanStartConfig/with_links-10                           96.00 ± 0%      0.00 ± 0%  -100.00% (p=0.000 n=10)
NewSpanStartConfig/with_links_set_multiple_times-10        272.0 ± 0%     176.0 ± 0%   -35.29% (p=0.000 n=10)
NewSpanStartConfig/with_new_root-10                        0.000 ± 0%     0.000 ± 0%         ~ (p=1.000 n=10) ¹
NewSpanStartConfig/with_span_kind-10                       0.000 ± 0%     0.000 ± 0%         ~ (p=1.000 n=10) ¹
geomean                                                               ²               ?                       ² ³
¹ all samples are equal
² summaries must be >0 to compute geomean
³ ratios must be >0 to compute geomean

                                                         │  bench-main  │              bench-branch               │
                                                         │  allocs/op   │ allocs/op   vs base                     │
NewSpanStartConfig/with_no_options-10                      0.000 ± 0%     0.000 ± 0%         ~ (p=1.000 n=10) ¹
NewSpanStartConfig/with_attributes-10                      1.000 ± 0%     0.000 ± 0%  -100.00% (p=0.000 n=10)
NewSpanStartConfig/with_attributes_set_multiple_times-10   2.000 ± 0%     1.000 ± 0%   -50.00% (p=0.000 n=10)
NewSpanStartConfig/with_a_timestamp-10                     0.000 ± 0%     0.000 ± 0%         ~ (p=1.000 n=10) ¹
NewSpanStartConfig/with_links-10                           1.000 ± 0%     0.000 ± 0%  -100.00% (p=0.000 n=10)
NewSpanStartConfig/with_links_set_multiple_times-10        2.000 ± 0%     1.000 ± 0%   -50.00% (p=0.000 n=10)
NewSpanStartConfig/with_new_root-10                        0.000 ± 0%     0.000 ± 0%         ~ (p=1.000 n=10) ¹
NewSpanStartConfig/with_span_kind-10                       0.000 ± 0%     0.000 ± 0%         ~ (p=1.000 n=10) ¹
geomean                                                               ²               ?                       ² ³
¹ all samples are equal
² summaries must be >0 to compute geomean
³ ratios must be >0 to compute geomean
```

```
pkg: go.opentelemetry.io/otel/trace
                                                     │ bench-main  │            bench-branch             │
                                                     │   sec/op    │   sec/op     vs base                │
NewEventConfig/with_no_options-10                      45.94n ± 1%   46.27n ± 1%        ~ (p=0.110 n=10)
NewEventConfig/with_attributes-10                      80.70n ± 1%   50.22n ± 1%  -37.77% (p=0.000 n=10)
NewEventConfig/with_attributes_set_multiple_times-10   143.3n ± 2%   109.3n ± 2%  -23.73% (p=0.000 n=10)
NewEventConfig/with_a_timestamp-10                     14.74n ± 1%   14.76n ± 2%        ~ (p=0.270 n=10)
NewEventConfig/with_a_stacktrace-10                    54.60n ± 2%   54.69n ± 2%        ~ (p=0.670 n=10)
geomean                                                53.23n        45.96n       -13.66%

                                                     │  bench-main  │              bench-branch               │
                                                     │     B/op     │    B/op     vs base                     │
NewEventConfig/with_no_options-10                      0.000 ± 0%     0.000 ± 0%         ~ (p=1.000 n=10) ¹
NewEventConfig/with_attributes-10                      64.00 ± 0%      0.00 ± 0%  -100.00% (p=0.000 n=10)
NewEventConfig/with_attributes_set_multiple_times-10   192.0 ± 0%     128.0 ± 0%   -33.33% (p=0.000 n=10)
NewEventConfig/with_a_timestamp-10                     0.000 ± 0%     0.000 ± 0%         ~ (p=1.000 n=10) ¹
NewEventConfig/with_a_stacktrace-10                    0.000 ± 0%     0.000 ± 0%         ~ (p=1.000 n=10) ¹
geomean                                                           ²               ?                       ² ³
¹ all samples are equal
² summaries must be >0 to compute geomean
³ ratios must be >0 to compute geomean

                                                     │  bench-main  │              bench-branch               │
                                                     │  allocs/op   │ allocs/op   vs base                     │
NewEventConfig/with_no_options-10                      0.000 ± 0%     0.000 ± 0%         ~ (p=1.000 n=10) ¹
NewEventConfig/with_attributes-10                      1.000 ± 0%     0.000 ± 0%  -100.00% (p=0.000 n=10)
NewEventConfig/with_attributes_set_multiple_times-10   2.000 ± 0%     1.000 ± 0%   -50.00% (p=0.000 n=10)
NewEventConfig/with_a_timestamp-10                     0.000 ± 0%     0.000 ± 0%         ~ (p=1.000 n=10) ¹
NewEventConfig/with_a_stacktrace-10                    0.000 ± 0%     0.000 ± 0%         ~ (p=1.000 n=10) ¹
geomean                                                           ²               ?                       ² ³
¹ all samples are equal
² summaries must be >0 to compute geomean
³ ratios must be >0 to compute geomean
```

### CODE REVIEW

**Comment by MrAlias** [comment]
Where are these benchmarks defined? I'm not able to locate them.

**Comment by dmathieu** [comment]
As the description says, they're coming from #5566 :)

**Review by pellared — APPROVED** [review]

**Review by hanyuancheung — APPROVED** [review]

**Review by dashpole — APPROVED** [review]

**Review by MrAlias — CHANGES_REQUESTED** [review]
This fundamentally changes the mutability of the underlying span. Prior to these changes the follow passes:

```go
func TestMutability(t *testing.T) {
	a := attribute.String("a", "b")
	b := attribute.String("b", "b")
	attrs := []attribute.KeyValue{a, b}
	c := NewSpanStartConfig(WithAttributes(attrs...))

	attrs[0] = attribute.String("c", "b")

	assert.Equal(t, SpanConfig{attributes: []attribute.KeyValue{a, b}}, c)
}
```

This will introduce a breaking behavior change to a stable API.

**Comment by dmathieu** [comment]
Closing, as the mutability requirement makes the alloc unavoidable.

**Pull request closed without merging**
