### PR TITLE
Add evantorrie as an approver

### PR DESCRIPTION
**Pull request by jmacd**
## [Requirements](https://github.com/open-telemetry/community/blob/master/community-membership.md#requirements-1)
- [X]  >=10 substantive contributions
   - https://github.com/open-telemetry/opentelemetry-go/graphs/contributors
- [X]  Active >1mo
- [X]  add to CODEOWNERS  (done in this pull)
- [X]  Add to CONTRIBUTING.md (done in this pull)
- [X]  Maintainer nomination
   - @jmacd :heavy_check_mark: 
   - @MrAlias  :heavy_check_mark: 
- [x]  Add to @open-telemetry/go-approvers

### CODE REVIEW

**Comment by lizthegrey** [comment]
When was @evantorrie added as an approver?

**Comment by jmacd** [comment]
It was a while ago. 
https://github.com/open-telemetry/community/issues/337

(I am starting to understand the complicated process of adding an approver.)

**Comment by MrAlias** [comment]
@jmacd I think that PR was just adding him to the OTel community. I wasn't aware of the approver nomination.

I'm not opposed, but don't know if the requirements are meat.

**Comment by jmacd** [comment]
Oh. See, apparently I still do not understand the complicated process.
Is this documented somewhere? (Ahhh!)
I nominate evantorrie and he's met the requirements.
https://github.com/open-telemetry/opentelemetry-go/pulls?q=is%3Apr+is%3Aclosed+author%3Aevantorrie

**Comment by lizthegrey** [comment]
https://github.com/open-telemetry/opentelemetry-go/pull/687 is a current checklist

**Comment by Aneurysm9** [comment]
Process details are documented at https://github.com/open-telemetry/community/blob/master/community-membership.md#approver.

**Comment by MrAlias** [comment]
> Oh. See, apparently I still do not understand the complicated process.
> Is this documented somewhere? (Ahhh!)
> I nominate evantorrie and he's met the requirements.
> https://github.com/open-telemetry/opentelemetry-go/pulls?q=is%3Apr+is%3Aclosed+author%3Aevantorrie

This looks correct to me. Have we verified that @evantorrie wants the approver status?

I'm good with updating this PR to match #687 and make it official if he is.

**Comment by jmacd** [comment]
@evantorrie Can you confirm that you are interested in becoming an approver? I thought this was the case, but I could be mistaken.

**Comment by evantorrie** [comment]
@jmacd Oops, sorry.  Was AFK for a couple of days. Originally I just had asked for membership status, because I didn't have that - but I am happy to take on Approver as well if you feel I meet the requirements.

**Pull request merged**
