### PR TITLE
Handle empty env vars as it they were not set

### PR DESCRIPTION
**Pull request by pellared**
## Why

> The SDK MUST interpret an empty value of an environment variable the same way as when the variable is unset.

Reference: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md#parsing-empty-value

## What

1. Handle empty env vars as it they were not set (in `sdk/internal/env/env.go`)

    Currently when empty value is set then it is logging info (e.g. for `_LIMIT` env vars) and fallbacks to the default value. After this change it will not longer log.

2. Opportunistic refactor: simplify `envOr` function in `jaeger` and `zipkin` packages.

I do not think it is worth mentioning in the changelog.

### CODE REVIEW

**Comment by dmathieu** [comment]
Shouldn't there be tests?

**Review by hanyuancheung — APPROVED** [review]

**Comment by pellared** [comment]
> Shouldn't there be tests?

I would prefer to (refactor) centralize the env var parsing code in an internal package. Then the common helper function could have unit tests.

Probably a new package should be `internal/env` as `exporters/*` would not have access to `sdk/internal/env`...

**Comment by pellared** [comment]
> Shouldn't there be tests?

Addressed in https://github.com/open-telemetry/opentelemetry-go/pull/3805

**Comment by pellared** [comment]
Superseded by https://github.com/open-telemetry/opentelemetry-go/pull/3805

**Comment by pellared** [comment]
Reopening because of [this](https://github.com/open-telemetry/opentelemetry-go/pull/3805#pullrequestreview-1315968958) comment 

CC @Aneurysm9

**Comment by Aneurysm9** [comment]
Implementation looks fine.  I agree that it needs tests and I'm not sure if skipping a changelog entry is correct here.  This is a change in behavior and may have subtle impacts on end users.

**Comment by pellared** [comment]
@Aneurysm9 @dmathieu 

Missing test added https://github.com/open-telemetry/opentelemetry-go/pull/3764/commits/7369e62b8bd6d733f91b0d398ba67e1ccab47cac

Changelog entry added https://github.com/open-telemetry/opentelemetry-go/pull/3764/commits/562cdb0b26be0de7590347a1904ffa23db6c9f65

**Review by dmathieu — APPROVED** [review]

**Review by Aneurysm9 — APPROVED** [review]

**Review by MrAlias — APPROVED** [review]

**Pull request merged**
