### PR TITLE
Remove unused prometheus exporter options, can be added later

### PR DESCRIPTION
**Pull request by bogdandrutu**
For the moment they only confuse users.

Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>

### CODE REVIEW

**Review by Aneurysm9 — CHANGES_REQUESTED** [review]
The current implementation is in line with our style guide and provides consistency among components.  The `New()` function signature cannot be changed once this module is in a stable module set and thus I think it best to leave it as it is.

**Comment by bogdandrutu** [comment]
You are saying that you cannot add a variadic argument to a function?

**Comment by Aneurysm9** [comment]
> You are saying that you cannot add a variadic argument to a function?

[That's correct](https://go.googlesource.com/exp/+/master/apidiff/README.md#functions).  Adding a variadic parameter to a function changes its signature in a way that is incompatible with assignment to a value that does not have the variadic argument, even if it would be compatible at call sites.

**Comment by bogdandrutu** [comment]
I understand what is the effect, but you want to guarantee that?

**Pull request closed without merging**
