### PR TITLE
Add Go 1.17 to testing matrix

### PR DESCRIPTION
**Pull request by Aneurysm9**
Signed-off-by: Anthony J Mirabella <a9@aneurysm9.com>

### CODE REVIEW

**Review by MrAlias — CHANGES_REQUESTED** [review]
This is a breaking change. If a user was building this project with Go 1.15 before these changes, their build will be broken after. I do not think we can make this change now that we have made a stable release. Right?

**Comment by Aneurysm9** [comment]
> This is a breaking change. If a user was building this project with Go 1.15 before these changes, their build will be broken after. I do not think we can make this change now that we have made a stable release. Right?

I don't think that this breaks building with 1.15, it just stops testing against it and increases the minimum supported version.  We need the ability to increase the minimum supported version and cannot be tethered to 1.15 long after upstream support has ceased (which has already happened with the release of 1.17).

**Review by pellared — APPROVED** [review]

**Comment by MadVikingGod** [comment]
This shouldn't break any 1.15 builds, it would be using 1.16 features that
would do that. This should only give a warning for any project that is 1.15

+1

**Comment by bogdandrutu** [comment]
If the intent is to still support go 1.15 you need to continue to build/test with go 1.15 otherwise you cannot guarantee that you will not start using go 1.16 features that will break go 1.15

Also removing support for a specific go version should not be a breaking change, see gRPC-go does that https://github.com/grpc/grpc-go/commits/master/go.mod, but you probably need to announce it.

**Comment by bogdandrutu** [comment]
@MrAlias you cannot stay on a super old version forever, especially with golang being very active and releasing new versions/features very often. Probably would be good to clarify what are the things the project guarantees.

**Comment by Aneurysm9** [comment]
I seem to have misremembered [our prior conclusion](https://github.com/open-telemetry/opentelemetry-go/pull/1865#issuecomment-833863022) on this issue.  I will update this to only add testing for 1.17, but we should consider how we avoid being tethered to 1.15 forever.

**Review by MrAlias — APPROVED** [review]

**Review by dashpole — APPROVED** [review]

**Pull request merged**
