### PR TITLE
chore(ci): update Go versions

### PR DESCRIPTION
**Pull request by lizthegrey**
1.21.6 and 1.20.13 point releases are out now. Use them in CI.

### CODE REVIEW

**Comment by lizthegrey** [comment]
CI only change skips changelog I believe

**Comment by dmathieu** [comment]
I'm not sure this is necessary. The `~` should already make us use the latest patch release within the specified minor.

**Comment by pellared** [comment]
> I'm not sure this is necessary. The `~` should already make us use the latest patch release within the specified minor.

And we additionally have `check-latest: true`

**Comment by lizthegrey** [comment]
Ah, yes, so it does, even if the CI names are not descriptive.
Screenshot from 2024-01-16 11-53-57
Screenshot from 2024-01-16 11-53-46

**Comment by MrAlias** [comment]
Superseded by https://github.com/open-telemetry/opentelemetry-go/pull/4890?

**Pull request closed without merging**
