### PR TITLE
Drop support for Go 1.19

### PR DESCRIPTION
**Pull request by MrAlias**
Our last release added support for Go 1.21. Following our versioning policy, this drops support for the now unsupported version of Go (1.19).

### CODE REVIEW

**Review by dashpole — APPROVED** [review]
If we aren't testing go 1.19 anymore, is it correct to leave go.mod files on go 1.19?  Does the go.mod go version prevent us from using go 1.20 features?

**Review by MadVikingGod — APPROVED** [review]

**Comment by MrAlias** [comment]
> If we aren't testing go 1.19 anymore, is it correct to leave go.mod files on go 1.19? Does the go.mod go version prevent us from using go 1.20 features?

I was wanting to not bump all directives because that will force users to not use Go 1.19. But, you make a good point, that by not doing so we put users on Go 1.19 into a potentially false sense of hope. We are not guaranteeing their code will still compile, but we're also not making it clear why it fails when it doesn't.

I can update all the Go directives.

**Review by dmathieu — APPROVED** [review]

**Comment by pellared** [comment]
> This does not bump all module Go directives as they all still remain compatible with Go 1.19 (except for sdk/metric based on the removed comments).

How do you find which modules require a `go` directive bump and which are not needing it?

I am asking because (as far as I know and see when testing) if I revert the change in `example/fib/go.mod` so that it is `go 1.19` it still works when you have Go 1.20+ installed.

If the process is not automated then it can be error-prone and it may be safer to bump the `go` directive in all modules.

**Comment by MrAlias** [comment]
> > This does not bump all module Go directives as they all still remain compatible with Go 1.19 (except for sdk/metric based on the removed comments).
> 
> How do you find which modules require a `go` directive bump and which are not needing it?
> 
> I am asking because (as far as I know and see when testing) if I revert the change in `example/fib/go.mod` so that it is `go 1.19` it still works when you have Go 1.20+ installed.
> 
> If the process is not automated then it can be error-prone and it may be safer to bump the `go` directive in all modules.

All Go directives have already been updated: https://github.com/open-telemetry/opentelemetry-go/pull/4481/commits/76161d87a5492f2ef127ba4492ecdb05414a9b8b

https://github.com/open-telemetry/opentelemetry-go/pull/4481#pullrequestreview-1614013406

**Review by pellared — APPROVED** [review]

**Pull request merged**
