### PR TITLE
Add govet with atomicalign

### PR DESCRIPTION
**Pull request by pellared**
## What

- Add [`atomicalign`](https://pkg.go.dev/golang.org/x/tools/go/analysis/passes/atomicalign) analyzer as an additional safety net against https://golang.org/pkg/sync/atomic/#pkg-note-BUG 
- Execute `lint` workflow additionally with `GOARCH=386`

## Remarks

1. [`atomicalign`](https://pkg.go.dev/golang.org/x/tools/go/analysis/passes/atomicalign) analyzer works only on 32bit arch: https://cs.opensource.google/go/x/tools/+/refs/tags/v0.1.3:go/analysis/passes/atomicalign/atomicalign.go;l=33-35. Here I checked that it works on x86: https://github.com/open-telemetry/opentelemetry-go/pull/2008/checks?check_run_id=2838943826
2. `atomicalign` only finds simple cases. We should not rely on it
3. In general most problems with `atomic` usage should be detected by `ci / compatibility-test` jobs (runtime panics)

### CODE REVIEW

**Comment by pellared** [comment]
> Please add a CHANGELOG entry, or add the "Skip Changelog" label if not required.

😉

**Comment by MrAlias** [comment]
> `atomicalign` only finds simple cases. We should not rely on it
> In general most problems with `atomic` usage should be detected by `ci / compatibility-test` jobs (runtime panics)

I'm not following this. The project added atomic alignment tests to avoid such panics at runtime. They were non-descriptive, not deterministically triggered, and caused a lot of issues.

Currently we have curated alignment tests. If we want to switch to this analyzer it should support more than just simple cases and be a replacement for the existing solution. If it is not, I do not agree that the switch is worth making.

**Comment by pellared** [comment]
> I'm not following this. The project added atomic alignment tests to avoid such panics at runtime. They were non-descriptive, not deterministically triggered, and caused a lot of issues.

The panic at runtime can still happen. Here is an example: https://github.com/open-telemetry/opentelemetry-go/runs/2839025678 . However, the panic is very descriptive.

> Currently we have curated alignment tests. If we want to switch to this analyzer it should support more than just simple cases and be a replacement for the existing solution. If it is not, I do not agree that the switch is worth making.

I do not say that we should get rid of the alignment tests. I just think that we can have it as an additional safety net. The `atomicalign` MAY help prevent bugs if one forgets to write an alignment test. Also, I think its output is far superior. See an example here: https://github.com/open-telemetry/opentelemetry-go/runs/2851467579

**Comment by pellared** [comment]
Please let me know if you do think that introducing the `atomicalign` analyzer is worth it's value.

If yes, then I can update the branch and get rid of intentional bugs.

If not, then feel free to close the PR.

**Comment by MrAlias** [comment]
Thanks for opening this, but I do not see the necessary motivation to include these changes at this time. There appears an added benefit to including the analyzer as it provides dynamic inventory of the code and then validation. However, given we have a working solution to this and the included changes are not being submitted with the intent that and documentation of how this is a drop in replacement existing solution I do not want to include these changes at this point.

Please feel free to resubmit the changes if they can be verified to replace the existing solution and provide additional benefit to the project. Ideally, this would be documented and presented in a SIG meeting agenda item or an issue.

**Pull request closed without merging**
