### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by MrAlias**
- Bump github.com/golangci/golangci-lint from 1.42.1 to 1.43.0 in /internal/tools (supersedes and closes #2368)
- Bump google.golang.org/grpc from 1.41.0 to 1.42.0 in /exporters/otlp/otlpmetric (supersedes and closes #2367)
- Bump go.opentelemetry.io/proto/otlp from 0.9.0 to 0.10.0 in /exporters/otlp/otlpmetric/otlpmetrichttp (supersedes and closes #2366)
- Bump go.opentelemetry.io/proto/otlp from 0.9.0 to 0.10.0 in /exporters/otlp/otlpmetric (supersedes and closes #2365)
- Bump go.opentelemetry.io/proto/otlp from 0.9.0 to 0.10.0 in /exporters/otlp/otlptrace (supersedes and closes #2364)
- Bump google.golang.org/grpc from 1.41.0 to 1.42.0 in /exporters/otlp/otlpmetric/otlpmetricgrpc (supersedes and closes #2363)
- Bump google.golang.org/grpc from 1.41.0 to 1.42.0 in /exporters/otlp/otlptrace (supersedes and closes #2362)
- Bump go.opentelemetry.io/proto/otlp from 0.9.0 to 0.10.0 in /exporters/otlp/otlptrace/otlptracehttp (supersedes and closes #2361)
- Bump google.golang.org/grpc from 1.41.0 to 1.42.0 in /exporters/otlp/otlptrace/otlptracegrpc (supersedes and closes #2360)
- Bump go.opentelemetry.io/proto/otlp from 0.9.0 to 0.10.0 in /exporters/otlp/otlpmetric/otlpmetricgrpc (supersedes and closes #2359)
- Bump go.opentelemetry.io/proto/otlp from 0.9.0 to 0.10.0 in /exporters/otlp/otlptrace/otlptracegrpc (supersedes and closes #2358)
- Bump github.com/benbjohnson/clock from 1.1.0 to 1.2.0 in /sdk/metric (supersedes and closes #2357)
- Bump google.golang.org/grpc from 1.41.0 to 1.42.0 in /example/otel-collector (supersedes and closes #2356)

### CODE REVIEW

**Comment by MrAlias** [comment]
Looks like golangci-lint requires Go 1.16+

**Comment by Aneurysm9** [comment]
> Looks like golangci-lint requires Go 1.16+

We should discuss this at the SIG meeting today.  I think we can't maintain compatibility with older versions indefinitely and I expect to see many projects require 1.17 once 1.16 isn't supported upstream due to the improvements in module handling.

**Comment by MrAlias** [comment]
> > Looks like golangci-lint requires Go 1.16+
> 
> We should discuss this at the SIG meeting today. I think we can't maintain compatibility with older versions indefinitely and I expect to see many projects require 1.17 once 1.16 isn't supported upstream due to the improvements in module handling.

Agreed.

**Review by Aneurysm9 — APPROVED** [review]

**Comment by MadVikingGod** [comment]
I noted that lint did require 1.16 that, but that is only a part of our "build" process.  Because the API or SDK don't import golangci-lint, go 1.15 should still be able to use them as a library.  We just have to bump our test "build" platforms.

**Review by evantorrie — APPROVED** [review]

**Comment by MrAlias** [comment]
I really don't get how it worked for https://github.com/open-telemetry/opentelemetry-go/pull/2376 but not this ...

**Comment by Aneurysm9** [comment]
I wonder if it is because Dependabot is still the author of commits on the branch.  I pulled this into https://github.com/open-telemetry/opentelemetry-go/pull/2377 and it is doing the same thing there.

**Comment by MrAlias** [comment]
> I wonder if it is because Dependabot is still the author of commits on the branch. I pulled this into #2377 and it is doing the same thing there.

Interesting, I'll try collapsing this and see if that works.

**Comment by MrAlias** [comment]
It looks like I got a working version in https://github.com/open-telemetry/opentelemetry-go/pull/2378. It might be the merges of main from the GitHub console that are causing the problem. Not 100%, but in the linked PR when I did that it failed to run the EasyCI check. Likely relevant for https://github.com/open-telemetry/opentelemetry-go/pull/2373.

**Pull request closed without merging**
