### PR TITLE
Remove runtime/trace task tracker for Go 1.11

### PR DESCRIPTION
**Pull request by MrAlias**
This project has a minimum support guarantee for Go 1.14. This removes code specific to Go 1.11 and the dedicated task runner used in that version.

This was code inherited from OpenCensus. If we want to add more detailed support for this we can do so after GA in an OpenTelemetry specific manner.

### CODE REVIEW

**Review by dashpole — APPROVED** [review]

**Comment by Aneurysm9** [comment]
Do we want to remove this, or just the [non-Go1.11 implementation](https://github.com/open-telemetry/opentelemetry-go/pull/1469/files#diff-3671bcede62b5dd967f9eca027a0c85d281d9b6a58a58b391d6bc5a05c320c63) and [Go 1.11 build flag](https://github.com/open-telemetry/opentelemetry-go/pull/1469/files#diff-677e0a6e0442b63b9ca9f6c91a754b9dbdf66b8a486697e47a0c19af9d81dad4L15)?  The support in the `runtime` package is now there in all supported Go versions.

This is a small, but potentially useful feature that has no public API so we've definitely got flexibility in deciding how we provide it.  I'm not opposed to removing it entirely to potentially return at a later date, but I want to make sure we're not just doing so based on a misunderstanding of the build flags used to avoid compiler errors when building with pre-1.11 compilers.

**Comment by MrAlias** [comment]
> Do we want to remove this, or just the [non-Go1.11 implementation](https://github.com/open-telemetry/opentelemetry-go/pull/1469/files#diff-3671bcede62b5dd967f9eca027a0c85d281d9b6a58a58b391d6bc5a05c320c63) and [Go 1.11 build flag](https://github.com/open-telemetry/opentelemetry-go/pull/1469/files#diff-677e0a6e0442b63b9ca9f6c91a754b9dbdf66b8a486697e47a0c19af9d81dad4L15)? The support in the `runtime` package is now there in all supported Go versions.

That's a good question. I was assuming since this is a no-op unless you build with Go 1.11, which we do not support, this was all just unused code. If you use the runtime trace package with out builds you will see the span creation task, but there never is a dedicated workflow task that is named the same as the span. If we removed the build flag it would in effect be adding the feature back in.

> This is a small, but potentially useful feature that has no public API so we've definitely got flexibility in deciding how we provide it. I'm not opposed to removing it entirely to potentially return at a later date, but I want to make sure we're not just doing so based on a misunderstanding of the build flags used to avoid compiler errors when building with pre-1.11 compilers.

It was my idea to come back to this later when we have a better understanding of the user needs for this. Given it isn't being used currently, it would be nice to have the project used for a bit and maybe provide a more informed solution (or none) here.

That all said I don't have strong feelings here. I was hoping to just clean up the unused code more than anything.

**Review by XSAM — APPROVED** [review]

**Comment by MrAlias** [comment]
We need to double check the build flags are exclusive or if they are that version or greater.

**Comment by Aneurysm9** [comment]
> a term for each Go major release, through the current version:
>  "go1.1" from Go version 1.1 onward, "go1.12" from Go 1.12, and so on

https://golang.org/cmd/go/#hdr-Build_constraints

It looks like these build tags should be interpreted as minimum required versions and not exact versions.

**Comment by MrAlias** [comment]
Will try again with just removing the build flags.

**Pull request closed without merging**
