### PR TITLE
No memory leakage in attributes filter

### PR DESCRIPTION
**Pull request by regeda**
The attributes filter collects seen attributes in order to avoid filtration on the same attribute set. However, the `attribute.Set` is not comparable type and new allocations of sets with same attributes will be considered as new sets.

Metrics with a high cardinality of attributes consume a lot of memory even if we set a filter to reduce that cardinality.

### CODE REVIEW

**Comment by MrAlias** [comment]
> However, the `attribute.Set` is not comparable type

Hmm, that's new. I guess if you have more than 10 attributes or those attributes have the new slice values they will compare the pointer values not the underlying values. This is a bug for other parts of the SDK as well.

**Review by MrAlias — COMMENTED** [review]
This seems reasonable to me.

If I recall correctly this map was added to act as a cache and reduce computation. If removing it helps reduce ever-expanding memory overhead at the cost of having to calculate the filter each time that seems reasonable to me.

@MadVikingGod thoughts?

**Review by MrAlias — APPROVED** [review]

**Review by hanyuancheung — APPROVED** [review]

**Comment by jmacd** [comment]
Aside:

> However, the attribute.Set is not comparable type and new allocations of sets with same attributes will be considered as new sets.

I do not believe this is true. The attribute.Set mechanism constructs a comparable array of KeyValue. For slice-valued Values, this process is carried out recursively -- slices are represented as arrays so they can be comparable.

The `attribute.Set` logic is tested correct above 10 attributes, it just falls back to use of `reflect` for >10 attributes in a set. The cost of attribute set construction is the cost of constructing a **specific-size array** of KeyValue.

If there's a bug in this logic, we should fix it -- or was the underlying issue really about accumulation of distinct sets? I take it from the fix in this PR that the underlying issue was true cardinality, not a failure of the attribute.Set logic. I'll be glad to help if there's a problem!

**Comment by MrAlias** [comment]
> Aside:
> 
> > However, the attribute.Set is not comparable type and new allocations of sets with same attributes will be considered as new sets.
> 
> I do not believe this is true. The attribute.Set mechanism constructs a comparable array of KeyValue. For slice-valued Values, this process is carried out recursively -- slices are represented as arrays so they can be comparable.
> 
> The `attribute.Set` logic is tested correct above 10 attributes, it just falls back to use of `reflect` for >10 attributes in a set. The cost of attribute set construction is the cost of constructing a **specific-size array** of KeyValue.
> 
> If there's a bug in this logic, we should fix it -- or was the underlying issue really about accumulation of distinct sets? I take it from the fix in this PR that the underlying issue was true cardinality, not a failure of the attribute.Set logic. I'll be glad to help if there's a problem!

Indeed https://github.com/open-telemetry/opentelemetry-go/issues/3702

We double checked this and the latest version of `attribute.Set` is comparable.

**Pull request merged**
