### PR TITLE
Upgrades dependencies

### PR DESCRIPTION
**Pull request by MadVikingGod**
This was done by using `go get -u -t ./...` for all directories with a go mod.  This will upgrade transitive dependencies, and if any were pinned.

~~This would supersede #3294 - #3338~~ resolved elsewhere.

### CODE REVIEW

**Comment by Aneurysm9** [comment]
All of the dependabot PRs were handled via https://github.com/open-telemetry/opentelemetry-go/pull/3348.  Would be interested to see the result of this approach after that.  I think it's just the transitive dependencies and those using pseudoversions.

**Comment by MadVikingGod** [comment]
I will redo this on the new main and see.

**Comment by pellared** [comment]
@MadVikingGod Can you run `go mod tidy`? 😉 I like this PR 👍

**Review by pellared — APPROVED** [review]

**Comment by Aneurysm9** [comment]
I think I see two categories of change here:

1. Updating a direct dependency on `google.golang.org/genproto` that dependabot doesn't upgrade, if I'm not mistaken because it does not deal with pseudoversions.
2. Updating transitive dependencies.

Definitely good with 1) but I'm not sure we need to/should do 2).  What are the risks and rewards of updating our transitive dependencies before they're updated where they are direct dependencies?

**Comment by MrAlias** [comment]
Should this be closed?

**Pull request closed without merging**
