### PR TITLE
Move exponential histogram mapping functions into top-level module

### PR DESCRIPTION
**Pull request by jmacd**
The exponential histogram mapping functions are not SDK-specific and have been until now included in the `sdk/metric` module, which is being swapped soon. Removing this non-SDK component allows it to be released without disruption as the metrics SDK is replaced.

Part of #2328 because that way the `sdk/metric/aggregator` directory can be removed completely.

### CODE REVIEW

**Comment by jmacd** [comment]
Note that we agreed to make public exponential-histogram mapping functions available in https://github.com/open-telemetry/opentelemetry-go/issues/2501; the code in `sdk/metric/aggregator/exponential/mapping` is not meant to disappear with the new metrics SDK.

**Comment by jmacd** [comment]
If we accept this PR, I will apply the same change of path to https://github.com/open-telemetry/opentelemetry-go/pull/3022 -- the `mapping` and `structure` packages are meant to be siblings.

**Review by MrAlias — CHANGES_REQUESTED** [review]
I do not think these packages have enough review or use to be included in a stable module just yet.

I think this package could fit into the new metric SDK.

**Comment by jmacd** [comment]
FWIW, we are using these mapping functions extensively (and exclusively) inside Lightstep.

**Comment by jmacd** [comment]
> enough review

For the record, those reviews were https://github.com/open-telemetry/opentelemetry-go/pull/2982 and https://github.com/open-telemetry/opentelemetry-go/pull/2502.

**Pull request closed without merging**
