### PR TITLE
Fix incorrect "all" and "resource" definition for Schema File

### PR DESCRIPTION
**Pull request by tigrannajaryan**
The "all" and "resource" sections had incorrect definitions of "attribute_rename" transform. It was missing the subkey "attribute_map".

This is a bug fix and makes the implementation compliant with the spec: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/schemas/file_format_v1.1.0.md#resources-section

Related issue: https://github.com/open-telemetry/opentelemetry-specification/issues/3245

### CODE REVIEW

**Comment by tigrannajaryan** [comment]
I think this does not require a change log since it is a bug fix, but let me know if you think otherwise.

**Review by MrAlias — APPROVED** [review]

**Comment by MrAlias** [comment]
> I think this does not require a change log since it is a bug fix, but let me know if you think otherwise.

Can you add an entry in the `### Fixed` section?

**Comment by tigrannajaryan** [comment]
> > I think this does not require a change log since it is a bug fix, but let me know if you think otherwise.
> 
> Can you add an entry in the `### Fixed` section?

Done.

**Review by Aneurysm9 — APPROVED** [review]

**Comment by tigrannajaryan** [comment]
OK to merge this?

**Comment by MrAlias** [comment]
> OK to merge this?

I think this meets the repo standard to wait a full 24 hours.

Is there a reason to expedite? Are we trying to push a build tools fix today?

**Review by hanyuancheung — APPROVED** [review]

**Comment by tigrannajaryan** [comment]
Rebased and conflict resolved. I think this is ready to be merged.

**Pull request merged**
