### PR TITLE
Add generics to metric instruments & instrument provider

### PR DESCRIPTION
**Pull request by leewoobin789**
There are no differences between float64 and int64 in each async instrument and sync instrument.

it would immensely help on simplifying the implementation of further features in go-contrib, avoiding many boilerplates.

### CODE REVIEW

**Comment by MrAlias** [comment]
> it would immensely help on simplifying the implementation of further features in go-contrib, avoiding many boilerplates.

Can you please justify this statement?

**Review by MrAlias — CHANGES_REQUESTED** [review]
This will not support users using Go < 1.18.

**Comment by leewoobin789** [comment]
@MrAlias 
fair point. however i suppose that the support under 1.18 is anyway abandoned in the current version, because the code ) already makes use of generics ( for instance [sdk/metric/instrument.go](https://github.com/open-telemetry/opentelemetry-go/blob/3b9862a771d2413a0cc787fd0ce219adef8531d1/sdk/metric/instrument.go#L59)). doesn't it?

The simplication could occur in the way that you don't need to define same function twice, when it comes to handling both int64 and float64 types.

Thanks!

p.s.
btw. somehow EasyCLA does not accept me as contributor. I have already registered as individual contributor in opentelemetry-collector-contrib, however I am facing a weird issue that redirects me back to my last (closed) PR in contrib repo.

**Comment by MrAlias** [comment]
> @MrAlias fair point. however i suppose that the support under 1.18 is anyway abandoned in the current version, because the code already makes use of generics ( for instance [sdk/metric/instrument.go](https://github.com/open-telemetry/opentelemetry-go/blob/3b9862a771d2413a0cc787fd0ce219adef8531d1/sdk/metric/instrument.go#L59)). doesn't it?

The SDK is a separate module from the API, it does not impose a limitation on the API. This is by design: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/overview.md.

Please see the existing discussion on the topic and the ultimate SIG decision: https://github.com/open-telemetry/opentelemetry-go/issues/2494#issuecomment-1116407799

**Comment by leewoobin789** [comment]
@MrAlias 
I see. Thank you for the information. I will close down this PR.

**Pull request closed without merging**
