### PR TITLE
CONTRIBUTING: fetch source in GOPATH mode

### PR DESCRIPTION
**Pull request by dolmen**
Fix clone command to fetch project source code using `go get` in `GOPATH` mode by using `GO111MODULE=off`.

### CODE REVIEW

**Comment by rghetia** [comment]
@dolmen please sign CLA.

**Comment by dolmen** [comment]
@lizthegrey I've signed the CLA.

**Comment by dolmen** [comment]
@MrAlias I agree. But in the mean time, the installation instructions for the project in its current state are not precise enough.

**Comment by rghetia** [comment]
> @MrAlias I agree. But in the mean time, the installation instructions for the project in its current state are not precise enough.

How about just remove the 'go get ..' instruction? The page already describes the alternate approach using git clone.

**Comment by paivagustavo** [comment]
I understand the point made here and I can see the instruction to install otel go has three cases:
1 - You're inside a module project and want to add the otel dependency, the instructions works fine;
2 - You're inside the GOPATH and wants to add a dependency to a project, the command will download the otel lib but will print a message;
3 - If you are outside of the GOPATH  and not inside a module project, the command will download the otel lib on the GOPATH but will print a message;

In all cases, the otel lib is actually downloaded but not all cases are really the correct one for "installing" otel. I would say that "installing" may be wrong part of the instructions because Otel is a lib, you can use/download/depend on the Otel lib and not install it. 

And for that reason the cases that fits with the project is 1 and 2. Reinforcing the point made by @MrAlias, go 1.13 already uses modules as default and I agree that we should support the recommended and default dependency management tool and for that case the instructions works fine.

There are some issues that may be related/fix this one such as #422 and #371, that may be a better approach to move with this issue.

**Comment by paivagustavo** [comment]
Also, if we disable go modules with `GO111MODULE=off`, it stop working on module projects, the dependency is _not_ added to `go.mod` at all.

**Comment by krnowak** [comment]
+1 for dropping the `go get` instructions in favor of `git clone`. I don't think we should document the standard workflow of adding a dependency on otel to user's project - it would be a imperfect duplication of go documentation anyway. This also means bonus points for not having to deal with some confusing messages and with GOPATH.

Also +1 for not recommending setting `GO111MODULES=off`. I'd say we support go 1.13 or higher, as go.mod states.

What I would also do is to add a short paragraph that when adding otel-go as a dependency to some project then the user should use `go.opentelemetry.io/otel`, not `github.com/open-telemetry/opentelemetry-go`.

**Comment by MrAlias** [comment]
I like the suggestions @krnowak outlined. I created #476 to track the task and any further discussions people wanted to include.

**Pull request closed without merging**
