### PR TITLE
feat(semconv): Add DeploymentEnvironmentKey to semconv package

### PR DESCRIPTION
**Pull request by seanschade**
I noticed the `deployment.environment` key was missing while instrumenting my applications.

https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/resource/semantic_conventions/deployment_environment.md

### CODE REVIEW

**Review by MrAlias — APPROVED** [review]

**Comment by MrAlias** [comment]
@seanschade I think the CLA bot is complaining because you do not have an email attached to the commits pushed. Can you check this and add on if not?

**Comment by seanschade** [comment]
> @seanschade I think the CLA bot is complaining because you do not have an email attached to the commits pushed. Can you check this and add on if not?

I initially had the wrong email associated which caused those issues, and then pushed a commit to fix it. It looks. like the EasyCLA check has passed.

**Comment by seanschade** [comment]
@MrAlias the CLA should be good to go now. Thanks.

**Comment by MrAlias** [comment]
@seanschade can you squash the commits into a single commit that is signed by the appropriate email and force push that to the branch to remove 078a5d0 from the commit list?

**Review by Aneurysm9 — APPROVED** [review]

**Comment by seanschade** [comment]
> @seanschade can you squash the commits into a single commit that is signed by the appropriate email and force push that to the branch to remove [078a5d0](https://github.com/open-telemetry/opentelemetry-go/commit/078a5d051fbdd565fd8a984c52ec0775fe701fa7) from the commit list?

Yes I can do that today.

**Review by MrAlias — APPROVED** [review]

**Comment by MrAlias** [comment]
Thanks for the contribution :smile:

**Pull request merged**
