### PR TITLE
freeze structs/arrays; disallow multidimensional arrays

### PR DESCRIPTION
**Pull request by lizthegrey**
See #949 and https://github.com/open-telemetry/opentelemetry-specification/issues/376#issuecomment-661068305

### CODE REVIEW

**Comment by lizthegrey** [comment]
Hm, https://github.com/open-telemetry/opentelemetry-proto/pull/157 says that yes, OTLP does intend to support nested arrays (even though the spec itself is silent on whether nested arrays are allowed). Let me rethink my approach here...

**Comment by lizthegrey** [comment]
https://github.com/open-telemetry/opentelemetry-specification/pull/596 says at the moment we are not required to support nested arrays. Out of simplicity, until that PR is passed, I think we should not support nested arrays, then :)

**Comment by lizthegrey** [comment]
Great, sorry about the delay, I'll get to it this week.

**Comment by MrAlias** [comment]
We talked about this PR today at the Go SIG meeting and we're wondering @lizthegrey if you need someone to take over this work?

Additionally, there were questions about the support of slices. Currently all the methods are named and work with arrays. This is a useful format to store the data in as it is very optimized for storage, but it is not the common type used. Instead, commonly slices are the type used and if we are returning an array (each a distinct type for each length of the array) users cannot handle these values in a generalized way. I.e. they cannot pass the return value to a function as the function needs to be defined to support all the types each array could be, instead they will need to convert the array back to a slice. It seems like we might provide a better API if we support this by default.

**Comment by lizthegrey** [comment]
Yeah, go ahead and take it over. I'm _almost_ done moving but not quite yet set up.

**Pull request closed without merging**
