### PR TITLE
Add workflow to check for presence of CHANGELOG changes on PRs

### LINKED ISSUE #932: automated advisory on CHANGELOG.md requirement
We should use GitHub Actions to put up a yellow warning if there's no CHANGELOG.md associated with a PR

### PR DESCRIPTION
**Pull request by Aneurysm9**
Fixes #932.

### CODE REVIEW

**Comment by Aneurysm9** [comment]
It looks like there may not be a way to mark the missing changelog as a warning rather than a failure.  Thoughts on whether that's ok?

**Comment by MrAlias** [comment]
> It looks like there may not be a way to mark the missing changelog as a warning rather than a failure. Thoughts on whether that's ok?

I think for 99% of PRs this will be fine. The times it will not will be for `dependabot` PRs (though this might be remediable), and administrative changes (changing approvers or maintainers is something I have been leaving out of the CHANGELOG as I didn't it relevant to the user).

I guess we could fix up the dependant stuff to add to the CHANGELOG and maybe also update this to see if the change was purely administrative (i.e. CODEOWNER was changed)? That or require CHANGELOG entries for the administrative stuff as well.

**Comment by evantorrie** [comment]
> I guess we could fix up the dependant stuff to add to the CHANGELOG and maybe also update this to see if the change was purely administrative (i.e. CODEOWNER was changed)? That or require CHANGELOG entries for the administrative stuff as well.

I'd be happy to do this (make dependencies auto-fix include adding to the changelog).

**Comment by Aneurysm9** [comment]
> > I guess we could fix up the dependant stuff to add to the CHANGELOG and maybe also update this to see if the change was purely administrative (i.e. CODEOWNER was changed)? That or require CHANGELOG entries for the administrative stuff as well.
> 
> I'd be happy to do this (make dependencies auto-fix include adding to the changelog).

If it can add a `Skip Changelog` label to dependencies issues then this check would ignore it.  I'm not sure how much value there is in including a list of dependency updates in the changelog.  Perhaps as useful but less cluttering would be a link to a PR search for dependabot PRs merged since the prior release date.

**Comment by evantorrie** [comment]
> If it can add a `Skip Changelog` label to dependencies issues then this check would ignore it. I'm not sure how much value there is in including a list of dependency updates in the changelog. Perhaps as useful but less cluttering would be a link to a PR search for dependabot PRs merged since the prior release date.

I tend to agree that less clutter re: dependabot version upgrades would be a better choice - especially as the project matures.

I created #1113 to track adding a `Skip Changelog` label.

**Comment by evantorrie** [comment]
@Aneurysm9 Could you create a "Skip Changelog" label with appropriate capitalization, etc?

I can then take on implementing #1113.

**Comment by Aneurysm9** [comment]
> @Aneurysm9 Could you create a "Skip Changelog" label with appropriate capitalization, etc?
> 
> I can then take on implementing #1113.

Label created.

**Pull request merged**
