### PR TITLE
Use gofumpt instead of gofmt

### PR DESCRIPTION
**Pull request by MrAlias**
[`gofumpt`](https://github.com/mvdan/gofumpt) is a stricter version of `gofmt`.

[Notably](https://github.com/mvdan/gofumpt#added-rules):

**No empty lines following an assignment operator**

```go
func foo() {
    foo :=
        "bar"
}
```

```go
func foo() {
	foo := "bar"
}
```

**No empty lines around function bodies**

```go
func foo() {

	println("bar")

}
```

```go
func foo() {
	println("bar")
}
```

**Functions should separate `) {` where the indentation helps readability**

```go
func foo(s string,
	i int) {
	println("bar")
}

// With an empty line it's slightly better, but still not great.
func bar(s string,
	i int) {

	println("bar")
}
```

```go
func foo(s string,
	i int,
) {
	println("bar")
}

// With an empty line it's slightly better, but still not great.
func bar(s string,
	i int,
) {
	println("bar")
}
```

**No empty lines around a lone statement (or comment) in a block**

```go
if err != nil {

	return err
}
```

```go
if err != nil {
	return err
}
```

**No empty lines before a simple error check**

```go
foo, err := processFoo()

if err != nil {
	return err
}
```

```go
foo, err := processFoo()
if err != nil {
	return err
}
```

**Composite literals should use newlines consistently**

```go
// A newline before or after an element requires newlines for the opening and
// closing braces.
var ints = []int{1, 2,
	3, 4}

// A newline between consecutive elements requires a newline between all
// elements.
var matrix = [][]int{
	{1},
	{2}, {
		3,
	},
}
```

```go
var ints = []int{
	1, 2,
	3, 4,
}

var matrix = [][]int{
	{1},
	{2},
	{
		3,
	},
}
```

**Empty field lists should use a single line**

```go
var V interface {
} = 3

type T struct {
}

func F(
)
```

```go
var V interface{} = 3

type T struct{}

func F()
```

**`std` imports must be in a separate group at the top**

```go
import (
	"foo.com/bar"

	"io"

	"io/ioutil"
)
```

```go
import (
	"io"
	"io/ioutil"

	"foo.com/bar"
)
```

**Short case clauses should take a single line**

```go
switch c {
case 'a', 'b',
	'c', 'd':
}
```

```go
switch c {
case 'a', 'b', 'c', 'd':
}
```

**Multiline top-level declarations must be separated by empty lines**

```go
func foo() {
	println("multiline foo")
}
func bar() {
	println("multiline bar")
}
```

```go
func foo() {
	println("multiline foo")
}

func bar() {
	println("multiline bar")
}
```

**Single var declarations should not be grouped with parentheses**

```go
var (
	foo = "bar"
)
```

```go
var foo = "bar"
```

**Contiguous top-level declarations should be grouped together**

```go
var nicer = "x"
var with = "y"
var alignment = "z"
```

```go
var (
	nicer     = "x"
	with      = "y"
	alignment = "z"
)
```

**Simple var-declaration statements should use short assignments**

```go
var s = "somestring"
```

```go
s := "somestring"
```

**The `-s` code simplification flag is enabled by default**

```go
var _ = [][]int{[]int{1}}
```

```go
var _ = [][]int{{1}}
```

**Octal integer literals should use the `0o` prefix on modules using Go 1.13 and later**

```go
const perm = 0755
```

```go
const perm = 0o755
```

**Comments which aren't Go directives should start with a whitespace**

```go
//go:noinline

//Foo is awesome.
func Foo() {}
```

```go
//go:noinline

// Foo is awesome.
func Foo() {}
```

**Composite literals should not have leading or trailing empty lines**

```go
var _ = []string{

	"foo",

}

var _ = map[string]string{

	"foo": "bar",

}
```

```go
var _ = []string{
	"foo",
}

var _ = map[string]string{
	"foo": "bar",
}
```

**Field lists should not have leading or trailing empty lines**

```go
type Person interface {

	Name() string

	Age() int

}

type ZeroFields struct {

	// No fields are needed here.

}
```

```go
type Person interface {
	Name() string

	Age() int
}

type ZeroFields struct {
	// No fields are needed here.
}
```

### CODE REVIEW

**Review by pellared — APPROVED** [review]
I love `gofumpt` and there is no need to convince me (I use it since `v0.1.0`) 😉 

PS. I see that there is still some formatting missing, but the CI anyway will make sure that you will fix it.

**Comment by MrAlias** [comment]
> PS. I see that there is still some formatting missing, but the CI anyway will make sure that you will fix it.

:eyes:

**Comment by MrAlias** [comment]
Hmm, something is not right. The things the lint CI system is failing about are things that are changed in this PR. E.g.

```
internal/matchers/expectation.go:30: File is not `gofumpt`-ed (gofumpt)
var (
	stackTracePruneRE = regexp.MustCompile(`runtime\/debug|testing|internal\/matchers`)
```

But that code has been updated ...

https://github.com/open-telemetry/opentelemetry-go/pull/4623/files#diff-09b360909f1478d1d88dd4d4ed14ff420f00e942adc10c28be6502ba60eefc47R30

**Comment by MrAlias** [comment]
I've cleared the cache (setup-go-Linux-ubuntu22-go-1.21.3-99cce1295de51406fce7c3295a6ae7b43748693bd678baabaf9da41cb6141ff8) and am not re-running the workflow to see if that was the issue.

**Comment by MrAlias** [comment]
> I've cleared the cache (setup-go-Linux-ubuntu22-go-1.21.3-99cce1295de51406fce7c3295a6ae7b43748693bd678baabaf9da41cb6141ff8) and am not re-running the workflow to see if that was the issue.

Nope: https://github.com/open-telemetry/opentelemetry-go/actions/runs/6512390140/job/17690052633

**Comment by pellared** [comment]
> I've cleared the cache (setup-go-Linux-ubuntu22-go-1.21.3-99cce1295de51406fce7c3295a6ae7b43748693bd678baabaf9da41cb6141ff8) and am not re-running the workflow to see if that was the issue.

I have run `make generate dependabot-check license-check lint vanity-import-check` on a new GitHub Codespace and I got the same error.

**Comment by pellared** [comment]
`go generate lint` reproduces the issue.

You need to format the `*.go.tmpl` files as well 🙈

**Review by hanyuancheung — APPROVED** [review]

**Pull request merged**
