### PR TITLE
sdk/log: Add filtering Processor example

### PR DESCRIPTION
**Pull request by pellared**
Towards https://github.com/open-telemetry/opentelemetry-go/issues/5065

### CODE REVIEW

**Review by dmathieu — APPROVED** [review]

**Comment by pellared** [comment]
@MrAlias, do you think it makes sense to add `MinSeverityProcessor` as an example? I feel uncertain as I would personally would prefer to have it as part of the SDK. However, I am not sure when it happens and this looks like a good example before we can add it.

The alternative was something like the following:

```go
func ExampleProcessor_filtering() {
	var processor logsdk.Processor = logsdk.NewBatchProcessor(nil)

	processor = ContextIgnoringProcessor{processor}

	_ = logsdk.NewLoggerProvider(
		logsdk.WithProcessor(processor),
	)
}

type key struct{}

var igoreLogsKey key

func WithIgnoreLogs(ctx context.Context) context.Context {
	return context.WithValue(ctx, igoreLogsKey, true)
}

func ignoreLogs(ctx context.Context) bool {
	_, ok := ctx.Value(igoreLogsKey).(bool)
	return ok
}

type ContextIgnoringProcessor struct {
	logsdk.Processor
}

func (p ContextIgnoringProcessor) OnEmit(ctx context.Context, record logsdk.Record) error {
	if ignoreLogs(ctx) {
		return nil
	}
	return p.Processor.OnEmit(ctx, record)
}

func (p ContextIgnoringProcessor) Enabled(ctx context.Context, record logsdk.Record) bool {
	return !ignoreLogs(ctx) && p.Enabled(ctx, record)
}
```

**Comment by MrAlias** [comment]
> @MrAlias, do you think it makes sense to add `MinSeverityProcessor` as an example?

I was planning to [add it to contrib](https://github.com/open-telemetry/opentelemetry-go-contrib/pull/5817). That way it can be used by users and when we want to stabilize it we can move it to the core repo.

**Comment by pellared** [comment]
@MrAlias, I will update the example to https://github.com/open-telemetry/opentelemetry-go/pull/5543#issuecomment-2194334650 then. Let me know if you have a better example proposal.

**Comment by pellared** [comment]
Ready for another round of reviews after rework.

**Review by MrAlias — APPROVED** [review]

**Review by dmathieu — APPROVED** [review]

**Pull request merged**
