### PR TITLE
Don't print nil if err is nil

### PR DESCRIPTION
**Pull request by TheYkk**

### CODE REVIEW

**Comment by dashpole** [comment]
Most examples of usage I can find in code check if the err is nil before calling handle.  Are there cases where we don't?  Either way, we should probably document that error is expected to be non-nil.

**Comment by TheYkk** [comment]
Ahh, I am using v0.20.0 and its was before https://github.com/open-telemetry/opentelemetry-go/commit/62cd933da58e67a565d1a11043223906fd2cfdd5#diff-6b5630aeace530fb9e933030a102bafbf0ceff99d37f7b1c77f7ef1cd7e90ec0 this update.

**Comment by Aneurysm9** [comment]
> Ahh, I am using v0.20.0 and its was before [62cd933#diff-6b5630aeace530fb9e933030a102bafbf0ceff99d37f7b1c77f7ef1cd7e90ec0](https://github.com/open-telemetry/opentelemetry-go/commit/62cd933da58e67a565d1a11043223906fd2cfdd5#diff-6b5630aeace530fb9e933030a102bafbf0ceff99d37f7b1c77f7ef1cd7e90ec0) this update.

Yeah, I think it might actually be useful to have this log nil errors just on the off chance that it actually helps us catch bugs like that.  I think it's worth documenting the expectation that handled errors be non-nil, as @dashpole suggests, but maybe we still print nil errors as an indicator that someone probably made a mistake elsewhere.  I'm not sure that bug would have been caught if the nil error was suppressed and then we wouldn't ever get actual errors printed.

**Comment by MadVikingGod** [comment]
Looking through our internal use, we never pass a nil error; it's either guarded by a `if err != nil` or a `fmt.Errorf()`.  But I think if a user passes a nil error, we should still print nil.  

To do otherwise would encourage code that doesn't check the error.

**Comment by MrAlias** [comment]
> Looking through our internal use, we never pass a nil error; it's either guarded by a `if err != nil` or a `fmt.Errorf()`. But I think if a user passes a nil error, we should still print nil.
> 
> To do otherwise would encourage code that doesn't check the error.

Agreed. @TheYkk please reopen if you think we missed something.

**Pull request closed without merging**
