### PR TITLE
Code Improvement - Error strings should not be capitalized

### PR DESCRIPTION
**Pull request by wgliang**
Code Improvement - Error strings should not be capitalized
https://github.com/golang/go/wiki/CodeReviewComments#error-strings

### CODE REVIEW

**Comment by XSAM** [comment]
Good catch. I found there are still many codes that have such issues. Should we also fix these parts?

e.g., 

https://github.com/open-telemetry/opentelemetry-go/blob/c066f15ed74fec52c4755014bfcf2bdfb8e0e661/exporters/otlp/otlphttp/driver.go#L196-L199

**Review by dashpole — APPROVED** [review]

**Comment by wgliang** [comment]
@XSAM Sure. I will fix the current errors and add the linter check to ensure that it will not continue to occur in the future.

**Comment by wgliang** [comment]
> Good catch. I found there are still many codes that have such issues. Should we also fix these parts?
> 
> e.g.,
> 
> https://github.com/open-telemetry/opentelemetry-go/blob/c066f15ed74fec52c4755014bfcf2bdfb8e0e661/exporters/otlp/otlphttp/driver.go#L196-L199

Done.

**Comment by wgliang** [comment]
/ping @XSAM and anyone who needs to review PRs.

**Review by XSAM — APPROVED** [review]
LGTM

**Comment by wgliang** [comment]
Who can merge this PR?

**Review by MrAlias — APPROVED** [review]

**Pull request merged**
