### PR TITLE
Use generic Sum, Gauge, and DataPoint value removing Value, Int64, and Float64 from metricdata

### PR DESCRIPTION
**Pull request by MrAlias**
The sum and last-value aggregations use generics over `int64` and `float64`. To satisfy the `Aggregator` interface they need to export `metricdata.Aggregator` types, respectively they produce a `metricdata.Sum` and `metricdata.Gauge`. Underlying these is the `metricdata.DataPoint` that has a `Value` field that can be either `metricdata.Int64` or `metricdata.Float64`. For the aggregator to convert between a generic value it stores to one of these types they will need to convert the value first to an `interface{}` and then type switch over them. For example:

```go
	switch interface{}(value).(type) {
	case int64:
		// Use metricdata.Int64.
	case float64:
		// Use metricdata.Float64.
	}
```

This means an allocation needs to be made to cast the value having potential to be slow, and, furthermore, be done in the collection path for all exporters for all sums and gauges.

Instead of doing this, the `metricdata.Sum`, `metricdata.Gauge`, and `metricdata.DataPoint` can use generics to match the aggregators. This will allow the assignment of the value directly.

### OTLP

The [OTLP uses similar concrete types generalized to an interface](https://github.com/open-telemetry/opentelemetry-proto-go/blob/bf078beef8c3ff8506ea4f7cf85cfa526ee9b359/otlp/metrics/v1/metrics.pb.go#L1179-L1193) to store data point values. This means that eventually, the above mentioned type switch will be necessary.

This change is not intended to alleviate the issue altogether, but instead push it as far down the processing chain as possible with the expectation that the cost will ultimately not be paid in many situation (e.g. different exporters).

### CODE REVIEW

**Comment by MadVikingGod** [comment]
Did this also break the fail metricdata tests?

**Comment by MrAlias** [comment]
> Did this also break the fail metricdata tests?

Right, forgot about that. Fixed.

**Comment by MrAlias** [comment]
Example usage: https://github.com/open-telemetry/opentelemetry-go/pull/3000/files#diff-12acd31cc033269be317c16835d2f75da31d39f97a1430c2e1e67c723628c14eR128-R133

**Review by MadVikingGod — APPROVED** [review]
The only concern I have with generics in our API is if we need to have a group of types across N, e.g. []Gague (with both int64 and float64).  As the API has settled, I think this is ok because of the Aggregation interface.

**Review by dashpole — APPROVED** [review]

**Pull request merged**
