### PR TITLE
Release v1.16.0/v0.39.0 -- Stable Metric API

### PR DESCRIPTION
**Pull request by MrAlias**
This release contains the first stable release of the OpenTelemetry Go [metric API]. Our project stability guarantees now apply to the `go.opentelemetry.io/otel/metric` package. See our [versioning policy](VERSIONING.md) for more information about these stability guarantees.

### Added

- The `go.opentelemetry.io/otel/semconv/v1.19.0` package. The package contains semantic conventions from the `v1.19.0` version of the OpenTelemetry specification. (#3848)
- The `go.opentelemetry.io/otel/semconv/v1.20.0` package. The package contains semantic conventions from the `v1.20.0` version of the OpenTelemetry specification. (#4078)

### Changed

- Use `strings.Cut()` instead of `string.SplitN()` for better readability and memory use. (#4049)

### Removed

- The deprecated `go.opentelemetry.io/otel/metric/instrument` package is removed. Use `go.opentelemetry.io/otel/metric` instead. (#4055)

### Fixed

- Fix build for BSD based systems in `go.opentelemetry.io/otel/sdk/resource`. (#4077)

[metric API]:https://pkg.go.dev/go.opentelemetry.io/otel/metric

### CODE REVIEW

**Review by pellared — APPROVED** [review]
👍

**Review by Aneurysm9 — APPROVED** [review]
🚀

**Review by XSAM — APPROVED** [review]
🥳

**Review by hanyuancheung — APPROVED** [review]
🚀

**Review by MadVikingGod — APPROVED** [review]

**Review by evantorrie — APPROVED** [review]
+1

**Review by dmathieu — APPROVED** [review]

**Review by dashpole — APPROVED** [review]

**Pull request merged**
