### PR TITLE
Misc fixes from PR 381

### PR DESCRIPTION
**Pull request by krnowak**
These are some fixes I found in #381. This PR is to shrink #381 a bit.

### CODE REVIEW

**Comment by lizthegrey** [comment]
ps @krnowak if you let maintainers edit your branches, it makes it easier to get things synced and promptly merged :)

**Comment by krnowak** [comment]
> ps @krnowak if you let maintainers edit your branches, it makes it easier to get things synced and promptly merged :)

Would love to, but for some reason this option not accessible for me neither here nor in PR creation page…

**Comment by lizthegrey** [comment]
> > ps @krnowak if you let maintainers edit your branches, it makes it easier to get things synced and promptly merged :)
> 
> Would love to, but for some reason this option not accessible for me neither here nor in PR creation page…

Likely an org setting, try asking Kinvolk admins if they'll turn that option in in your repo

**Comment by krnowak** [comment]
> > > ps @krnowak if you let maintainers edit your branches, it makes it easier to get things synced and promptly merged :)
> > 
> > 
> > Would love to, but for some reason this option not accessible for me neither here nor in PR creation page…
> 
> Likely an org setting, try asking Kinvolk admins if they'll turn that option in in your repo

I asked the admins, they couldn't find anything in neither org settings nor in repo settings. Heck, I even cloned opentelemetry-go to my own test org to figure it out, but I also couldn't find it nor the option was available to me. I also cloned opentelemetry-go to my personal account and the "allow edits from maintainers" option was available. So I suppose that this option is only available for PRs made from the repos in personal accounts.

**Comment by krnowak** [comment]
Rebased.

**Pull request merged**
