### PR TITLE
Add Marshaling implementations for exporters

### PR DESCRIPTION
**Pull request by MadVikingGod**
This change makes it so that the TracerProviders log messages will have the kind of exporter when logged.

There are differences between different exporters because each has different configurations and different levels of information that are accessible when the exporter will be logged.

### CODE REVIEW

**Review by Aneurysm9 — APPROVED** [review]

**Review by MrAlias — APPROVED** [review]

**Comment by dmathieu** [comment]
Should there be tests?

**Comment by MadVikingGod** [comment]
What behavior would you expect to test?  The marshaling logic is handled by the logr.  This just allows for the logs produced to be more detailed.

**Comment by dmathieu** [comment]
Not much I suppose, but checking that the method actually runs, and has the expected value?

**Review by pellared — APPROVED** [review]

**Comment by MadVikingGod** [comment]
Like I stated before, testing would not be testing our code but testing the code of `logr`.  So any test that I would write will test only our implementation, which is the recipe for a stale test.

**Comment by MrAlias** [comment]
From the SIG meeting yesterday there was a consensus that we likely do not want to test these additions. Doing so would be "change indicators" and likely contain more logic to validate than these additions.

That said, if someone wanted to propose changes after this is merged that test this output and didn't suffer from the issues above, we would be interested in reviewing them. There is a desire to not hold up these changes being merged because of this lack of associated tests.

**Pull request merged**
