### PR TITLE
Disables context-as-argument linter

### PR DESCRIPTION
**Pull request by MadVikingGod**
This is currently incompatible with viper v1.13.0. Status for the linter found at https://github.com/golangci/golangci-lint/issues/3280

### CODE REVIEW

**Review by Aneurysm9 — APPROVED** [review]

**Review by MrAlias — APPROVED** [review]
This doesn't upgrade golangci-lint to the latest version. Should it?

**Comment by MadVikingGod** [comment]
It doesn't need to. If you upgrade viper to v1.13.0, and have an old golangci it will still fail.

**Review by hanyuancheung — APPROVED** [review]

**Comment by MadVikingGod** [comment]
It was pinned in 1.50.1, but we don't have it pinned in `go-build-tools`.  If we upgrade that we will have the same problem.

**Comment by MrAlias** [comment]
> It was pinned in 1.50.1, but we don't have it pinned in `go-build-tools`. If we upgrade the build tools we will have the same problem.

If that's the case and we want to move forward with this can you sync with `main` so we can get this merged?

**Pull request merged**
