### PR TITLE
Move api/baggage to the propagators package

### PR DESCRIPTION
**Pull request by MrAlias**
Part of #1179 and #964

### CODE REVIEW

**Review by XSAM — APPROVED** [review]

**Comment by Aneurysm9** [comment]
This doesn't feel quite right to me.  Having the baggage map and context in the propagation package seems like it's putting too much into that package.  Seeing something like `propagation.MapFromContext()` or `propagation.NewContext()` doesn't make it clear to me that those are only related to the `Baggage` propagator.  I wonder whether it might be better to move just the `Baggage` propagator implementation to the `propagators` package and then move the rest to a `propagators/baggage` package.

**Comment by MrAlias** [comment]
> ... and then move the rest to a `propagators/baggage` package.

That seems reasonable to me. @Aneurysm9 what do you think about renaming those types/funcs? E.g. `MapFromBaggageContext()`, `NewBaggageContext`. The feedback we initially received was there were too many packages which makes me reluctant to persist a design that conceptually related code spans multiple packages. Thoughts?

**Comment by Aneurysm9** [comment]
> > ... and then move the rest to a `propagators/baggage` package.
> 
> That seems reasonable to me. @Aneurysm9 what do you think about renaming those types/funcs? E.g. `MapFromBaggageContext()`, `NewBaggageContext`. The feedback we initially received was there were too many packages which makes me reluctant to persist a design that conceptually related code spans multiple packages. Thoughts?

That could work as well.  Perhaps `Map` -> `BaggageMap` and `NewContext()` -> `ContextWithBaggage()`.  Applying the former everywhere would also lead to `ContextWithMap()` -> `ContextWithBaggageMap()`, which would seem to work well with a renamed `ContextWithBaggage()`.

**Comment by MrAlias** [comment]
Looking at this a bit more I think this is a place we might have over-engineered initially and is an opportunity to reduce the exported functionality of the API, lowering the long-term maintainer responsibility here. I'm going to see if things can be simplified.

**Review by jmacd — APPROVED** [review]

**Comment by MrAlias** [comment]
As discussed in the SIG meeting, I'm going to regroup on this and try to get another PR in that implements the Specification and accomplishes this move.

**Pull request closed without merging**
