### PR TITLE
Unary gRPC interceptors

### PR DESCRIPTION
**Pull request by iredelmeier**
Decided to move the streaming interceptors (well, the non-noop versions) out since there's a bit of funky behaviour in them.

This PR also contains a test tracer, which (unlikely the existing mock tracer) is both publicly exported and, more significantly, can be introspected to see details of what spans have been created. Currently, this change is mostly provided through separate commits, but could also be split into its own PR.

Similarly, there's some work around test assertions that are more powerful than what the standard library or `diff` provide. I personally see this as a temporary placeholder pending a separate discussion (started in SIG meetings) about using an assertion library - I **do not** think we should be in the business of maintaining our own!

### CODE REVIEW

**Comment by jmacd** [comment]
A large part of this PR is a mock trace testing framework. I wonder if we should split the PR? Otherwise the PR description should mention this in order to get the attention of more reviewers.

**Comment by lizthegrey** [comment]
Please split the testtracer and grpc pulls into separate pulls.

**Comment by bogdandrutu** [comment]
FYI: When we talked to the gRPC team some time ago they suggest to not use mocks to test gRPC code and better to us inmemory channel with real gRPC implementation. They said that gRPC is too complicated to be correctly mocked.

**Comment by jmacd** [comment]
We decided in the Go SIG meeting to close this for now.

**Pull request closed without merging**
