### PR TITLE
Run make precommit

### PR DESCRIPTION
**Pull request by MrAlias**
Looks like a the `go.sum` file has changes from running `go mod tidy`.

### CODE REVIEW

**Comment by dashpole** [comment]
I vaguely recall having to change my go version to 1.16 to make it pass ci/lint, and it made some go.sum changes IIRC

**Comment by MrAlias** [comment]
> I vaguely recall having to change my go version to 1.16 to make it pass ci/lint, and it made some go.sum changes IIRC

Interesting. Do you know what version you used to make it work?

I'm running 1.16.4 currently and it was proposing this change. I'm looking at testing in docker environments of other versions to see where this is coming from.

**Comment by MrAlias** [comment]
```bash
$ docker run --rm -v "$PWD":/usr/src/go.opentelemetry.io/otel -w /usr/src/go.opentelemetry.io/otel golang:1.16.4-buster make lint-modules  > /dev/null
$ git diff
diff --git a/example/passthrough/go.sum b/example/passthrough/go.sum
index aa2d32aa..382344ca 100644
--- a/example/passthrough/go.sum
+++ b/example/passthrough/go.sum
@@ -9,9 +9,7 @@ github.com/pmezard/go-difflib v1.0.0/go.mod h1:iKH77koFhYxTK1pcRnkKkqfTogsbg7gZN
 github.com/stretchr/objx v0.1.0/go.mod h1:HFkY916IF+rwdDfMAkV7OtwuqBVzrE8GR6GFx+wExME=
 github.com/stretchr/testify v1.7.0 h1:nwc3DEeHmmLAfoZucVR881uASk0Mfjw8xYJ99tb5CcY=
 github.com/stretchr/testify v1.7.0/go.mod h1:6Fq8oRcR53rry900zMqJjRRixrwX3KX962/h/Wwjteg=
-golang.org/x/xerrors v0.0.0-20191204190536-9bdfabe68543 h1:E7g+9GITq07hpfrRu66IVDexMakfv52eLZ2CXBWiKr4=
 golang.org/x/xerrors v0.0.0-20191204190536-9bdfabe68543/go.mod h1:I/5z698sn9Ka8TeJc9MKroUUfqBBauWjQqLJ2OPfmY0=
-gopkg.in/check.v1 v0.0.0-20161208181325-20d25e280405 h1:yhCVgyC4o1eVCa2tZl7eS0r+SDo693bJlVdllGtEeKM=
 gopkg.in/check.v1 v0.0.0-20161208181325-20d25e280405/go.mod h1:Co6ibVJAznAaIkqp8huTwlJQCZ016jof/cbN4VW5Yz0=
 gopkg.in/yaml.v3 v3.0.0-20200313102051-9f266ea9e77c h1:dUUwHk2QECo/6vqA44rthZ8ie2QXMNeKRTHCNY2nXvo=
 gopkg.in/yaml.v3 v3.0.0-20200313102051-9f266ea9e77c/go.mod h1:K4uyk7z7BCEPqu6E+C64Yfv1cQ7kz7rIZviUmN+EgEM=
```

```bash
$ docker run --rm -v "$PWD":/usr/src/go.opentelemetry.io/otel -w /usr/src/go.opentelemetry.io/otel golang:1.15.12-buster make lint-modules  > /dev/null
$ git diff
```

Looks like 1.16 is the cause.

**Comment by dashpole** [comment]
Ah, it was the other way around :).  Had to downgrade to 1.15...

**Pull request closed without merging**
