### PR TITLE
golangci lint fix

### PR DESCRIPTION
**Pull request by Petrie**

### CODE REVIEW

**Review by hanyuancheung — APPROVED** [review]

**Review by pellared — APPROVED** [review]

**Comment by dmathieu** [comment]
Is there a golangci config we should change so those issues fail the CI is they happen again?

**Comment by Petrie** [comment]
> Is there a golangci config we should change so those issues fail the CI is they happen again?

I'll try to solve this.

**Comment by Petrie** [comment]
I open a new pr https://github.com/open-telemetry/opentelemetry-go/pull/2987 to fix this lint error. with fix the CI exec abnormal phenomenon.

**Comment by MrAlias** [comment]
Is this still needed?

**Pull request closed without merging**
