### PR TITLE
Use function as config type instead of interface

### PR DESCRIPTION
**Pull request by chenjiandongx**
* Use function as config type instead of interface which will make code clean
* Add unit tests

### CODE REVIEW

**Comment by Aneurysm9** [comment]
Thank you for the contribution, however our [coding style guide requires](https://github.com/open-telemetry/opentelemetry-go/blob/main/CONTRIBUTING.md#option) that options be defined as an interface type.  For simple options we have in many cases opted for an [`optionFunc` implementation](https://github.com/open-telemetry/opentelemetry-go/blob/main/CONTRIBUTING.md#functional-options) of that interface.  If this PR were adapted to that pattern then we would be able to consider it.

**Comment by chenjiandongx** [comment]
@Aneurysm9 

After I file this PR, I found that not only the `basic` package has used the `Option interface`, but also other packages like `resource` / `histogram` / etc. I wonder is there a scenario that the `functional options pattern` could not match?

**Comment by MrAlias** [comment]
> I just wonder if there is a scenario that the functional options pattern could not match?

There indeed might be. [The link provided by @Aneurysm9](https://github.com/open-telemetry/opentelemetry-go/blob/main/CONTRIBUTING.md#functional-options) gives guidance on how to construct such an option and remain compliant with our style guidelines.

As @Aneurysm9 said, thanks for your interest in the project, but we are not able to accept these changes as they are in conflict with our community guidelines.

**Comment by Aneurysm9** [comment]
To add to what @MrAlias has said, we have indeed encountered situations where a simple function is insufficient.  See span start/end options and OTLP exporter options for examples.  We have made the conscious choice to us a more complicated form as our standard to ensure that we have the flexibility to handle those situations where they arise.  We have also made the choice to require that all option implementations follow the same pattern for consistency and maximal flexibility.

**Comment by chenjiandongx** [comment]
@MrAlias @Aneurysm9 thanks for the rapid reply 😄

Got it. Flexibility is important for such an industry project. I have read the guidance detailed and next time will obey the code styles it mentioned.

**Pull request closed without merging**
